#!/bin/bash


#assume changes added to index

#get changed file (from index)
FILE=`git diff --cached --name-only`
if [ -z "$FILE" ]
then
    echo "Add changes to index!"
    exit 1
fi
#echo $FILE

#get changed lines
LINES=`git blame $FILE |grep "Not Committed Yet"|awk -F"[()]" '{ print $2 }' | awk -F" " '{print $7}'`
#echo $BLAMELINES
#IFS=$'\n' read -d '' -r -a LINES < $BLAMELINES
#echo "${LINES[@]}"
#`git blame $FILE |grep "Not Committed Yet"|awk -F"[()]" '{ print $2 }' | awk -F" " '{print $7}'`
if [ -z "$LINES" ]
then
    echo "Failed to get changed lines!"
    exit 1
fi
#echo $LINE

# read all line numbers and get prev commit hash for each
LINESARR=($LINES)
for LINE in "${LINESARR[@]}"
do
    HASH=`git blame -L $LINE $FILE HEAD~1 |head -n1|awk '{ print $1 }'`
    if [ -z "$HASH" ]
    then
        echo "Failed to get previous commit hash for line $LINE"
        exit 1
    fi

    HASHESARR[ $i ]="$HASH"
    (( i++ ))
    #echo $HASH
done

FIRSTHASH=${HASHESARR[0]}
for HASH in "${HASHESARR[@]}"
do
    if [ "$FIRSTHASH" != "$HASH" ]
    then
        echo "Changes have different parent commit"
        echo $HASHESARR
        exit 1
    fi
done

echo $FIRSTHASH

