#!/bin/sh


#assume changes added to index

#get changed file (from index)
FILE=`git diff --cached --name-only`
if [ -z "$FILE" ]
then
    echo "Add changes to index!"
    exit 1
fi
#echo $FILE

#get changed line 
LINE=`git blame $FILE |grep "Not Committed Yet"|awk -F"[()]" '{ print $2 }' | awk -F" " '{print $7}'`
if [ -z "$LINE" ]
then
    echo "Failed to get changed line!"
    exit 1
fi
#echo $LINE

#git previous commit on that line
PRECOMMIT=`git blame -L $LINE $FILE HEAD~1 |head -n1|awk '{ print $1 }'`
if [ -z "$PRECOMMIT" ]
then
    echo "Failed to get previous commit for line"
    exit 1
fi
echo $PRECOMMIT

