#!/usr/bin/env bash
set -euo pipefail

# scaffold-doctor.sh — emit a stub doctor module for a target language.
#
# Phase 4 implementer agents currently start from a blank file per language.
# This script writes a compilable starter module with the canonical 10
# subcommands stubbed, the mutate() chokepoint declared, and the JSON output
# shape pre-wired so implementers fill in detector/fixer bodies, not plumbing.
#
# Usage:
#   scaffold-doctor.sh --target <dir> --tool <name> [--language <lang>] [--out <path>]
#
# Args:
#   --target <dir>    — target project root. Required.
#   --tool <name>     — binary name (used in CLI parser). Required.
#   --language <lang> — one of: rust|go|python|typescript. If omitted, auto-detect
#                       via discover-cli.sh.
#   --out <path>      — output file path. Default: <target>/<canonical-doctor-path>.
#                       Refuses to overwrite an existing file unless --force.
#   --force           — overwrite an existing file at --out.
#
# Exit codes: 0 on success, 64 usage, 66 target/lang not supported, 73 cant-create.
#
# This emits a SKELETON that compiles. Filling in detector/fixer bodies is
# Phase 4 work; the structural pieces (mutate chokepoint, exit codes, JSON
# shape, subcommand dispatch) are all done.

usage() {
    cat <<'USAGE_EOF' >&2
usage: scaffold-doctor.sh --target <dir> --tool <name> [--language <lang>] [--out <path>] [--force]
  --target   project root (required)
  --tool     binary/tool name (required)
  --language rust|go|python|typescript (auto-detected if omitted)
  --out      output file path (default: language-specific canonical location)
  --force    overwrite existing output
USAGE_EOF
}

target=""
tool=""
language=""
out_path=""
force=0
need_value() {
    [ -n "${2:-}" ] || { echo "scaffold-doctor: $1 requires a value" >&2; usage; exit 64; }
    case "$2" in --*) echo "scaffold-doctor: $1 requires a value, got option-like token: $2" >&2; usage; exit 64 ;; esac
}

while [ $# -gt 0 ]; do
    case "$1" in
        --target) need_value "$1" "${2:-}"; target="$2"; shift 2 ;;
        --tool)   need_value "$1" "${2:-}"; tool="$2"; shift 2 ;;
        --language) need_value "$1" "${2:-}"; language="$2"; shift 2 ;;
        --out)    need_value "$1" "${2:-}"; out_path="$2"; shift 2 ;;
        --force)  force=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "scaffold-doctor: unknown arg $1" >&2; usage; exit 64 ;;
    esac
done

if [ -z "$target" ] || [ -z "$tool" ]; then
    usage; exit 64
fi
[ -d "$target" ] || { echo "scaffold-doctor: $target not a directory" >&2; exit 66; }

# Auto-detect language if not specified.
if [ -z "$language" ]; then
    SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
    detect_json=$("$SKILL_DIR/scripts/discover-cli.sh" "$target" 2>/dev/null) || true
    language=$(printf '%s' "$detect_json" | python3 -c 'import json,sys
try:
    print(json.loads(sys.stdin.read()).get("language", ""))
except Exception:
    pass' 2>/dev/null || true)
fi

case "$language" in
    rust|go|python|typescript) ;;
    *)
        echo "scaffold-doctor: unsupported or undetected language '$language'" >&2
        echo "  supported: rust|go|python|typescript" >&2
        exit 66
        ;;
esac

# Determine canonical output path per language if not specified.
if [ -z "$out_path" ]; then
    case "$language" in
        rust)       out_path="$target/src/doctor.rs" ;;
        go)         out_path="$target/internal/doctor/doctor.go" ;;
        python)     out_path="$target/src/$(echo "$tool" | tr - _)/doctor.py" ;;
        typescript) out_path="$target/src/doctor.ts" ;;
    esac
fi

if [ -e "$out_path" ] && [ "$force" -ne 1 ]; then
    echo "scaffold-doctor: refusing to overwrite existing $out_path (use --force)" >&2
    exit 73
fi

# Ensure parent directory exists.
mkdir -p "$(dirname "$out_path")" \
    || { echo "scaffold-doctor: cant_create $(dirname "$out_path")" >&2; exit 73; }

emit_rust() {
    cat <<RUST_EOF
//! \`$tool doctor\` — self-healing diagnostics + fixers for $tool.
//!
//! SKELETON generated by scripts/scaffold-doctor.sh. Phase 4 implementer
//! fills in the detector/fixer bodies; structural plumbing is already wired.
//!
//! Contract:
//!   - 10 canonical subcommands: diagnose, fix, undo, explain, capabilities,
//!     health, robot-docs, gc, ls, diff.
//!   - All disk writes route through \`mutate(path, op)\` (the chokepoint).
//!   - Exit codes per the canonical 11 (see references/methodology/RFC.md).
//!   - JSON output per references/methodology/OUTPUT-SCHEMA.md.
//!   - Universal flags include --json, --robot, --quiet, --verbose/-v,
//!     --no-color, and --no-progress.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

/// Canonical exit codes (must match RFC.md § Section 4).
pub mod exit {
    pub const SUCCESS_OR_HEALTHY: u8 = 0;
    pub const FINDINGS_PRESENT_NO_FIX: u8 = 1;
    pub const FIX_PARTIAL: u8 = 2;
    pub const FIX_FAILED_ROLLED_BACK: u8 = 3;
    pub const REFUSED_UNSAFE: u8 = 4;
    pub const CONCURRENCY_LOST: u8 = 5;
    pub const ONLINE_REQUIRED: u8 = 6;
    pub const USAGE_ERROR: u8 = 64;
    pub const NO_INPUT: u8 = 66;
    pub const CANT_CREATE: u8 = 73;
    pub const IO_ERROR: u8 = 74;
}

/// The 7 canonical Op variants. Chown is optional and not implemented here.
#[derive(Debug, Clone)]
pub enum Op {
    WriteFile { content: Vec<u8>, mode: Option<u32> },
    AppendFile { content: Vec<u8> },
    Rename { target: PathBuf },
    Chmod { mode: u32 },
    SymlinkAtomic { target: PathBuf },
    DbExec { sql: String },
    DbMigrate { from: u32, to: u32 },
}

/// THE CHOKEPOINT. Every disk write under \`$tool doctor --fix\` MUST go
/// through this function. \`mutate-auditor\` (Phase 4 / Phase 7) verifies
/// this invariant via static analysis.
///
/// Responsibilities:
/// 1. Validate \`op\` is in \`capabilities.allowed_ops\` (closed set).
/// 2. Acquire per-path advisory lock (refuse with exit 5 if held > timeout).
/// 3. Compute \`before_hash\` of \`path\`.
/// 4. Backup the original to \`backups/\` (verbatim copy + sha256).
/// 5. Stage write to \`path.tmp.<run-id>\`.
/// 6. fsync; rename atomically; fsync parent dir.
/// 7. Compute \`after_hash\`; append \`actions.jsonl\` line.
pub fn mutate(_path: &Path, _op: Op) -> Result<(), DoctorError> {
    unimplemented!("Phase 4: implement mutate() per references/methodology/MUTATE-CHOKEPOINT.md")
}

#[derive(Debug)]
pub enum DoctorError {
    Refused(String),
    LockHeld { holder_pid: u32 },
    BackupFailed(String),
    OnlineRequired(String),
    Io(std::io::Error),
}

/// Top-level dispatch. Argument parsing should pin to clap; this is a stub.
pub fn run_doctor(args: Vec<String>) -> ExitCode {
    let subcommand = args.first().map(|s| s.as_str()).unwrap_or("diagnose");
    let rest = args.get(1..).unwrap_or(&[]);
    match subcommand {
        "diagnose" | "" => diagnose(rest),
        "fix" => fix(rest),
        "undo" => undo(rest),
        "explain" => explain(rest),
        "capabilities" => capabilities(rest),
        "health" => health(rest),
        "robot-docs" => robot_docs(rest),
        "gc" => gc(rest),
        "ls" => ls(rest),
        "diff" => diff(rest),
        _ => {
            eprintln!("$tool doctor: unknown subcommand '{}'", subcommand);
            ExitCode::from(exit::USAGE_ERROR)
        }
    }
}

// ---- Subcommand stubs (Phase 4 fills bodies) ----

fn diagnose(_args: &[String]) -> ExitCode {
    // Run all detectors; emit findings to stdout (text or JSON);
    // exit 0 if healthy, 1 if findings, 4 if refused.
    todo!("Phase 4: run detectors and emit findings")
}
fn fix(_args: &[String]) -> ExitCode {
    // Run detectors, then fixers (each routed through \`mutate()\`);
    // exit 0 if all fixed, 2 if partial, 3 if rolled back.
    todo!("Phase 4: run fixers")
}
fn undo(_args: &[String]) -> ExitCode {
    // Restore from \`.doctor/runs/<run-id>/backups/\`.
    todo!("Phase 4: restore from backups")
}
fn explain(_args: &[String]) -> ExitCode {
    // Expand a single finding ID with full evidence.
    todo!("Phase 4: explain a finding")
}
fn capabilities(_args: &[String]) -> ExitCode {
    // Print machine-readable contract (see assets/capabilities-template.json).
    todo!("Phase 4: emit capabilities --json")
}
fn health(_args: &[String]) -> ExitCode {
    // Cheap liveness summary; one line + exit code; < 200ms target.
    todo!("Phase 4: emit health one-liner")
}
fn robot_docs(_args: &[String]) -> ExitCode {
    // Self-contained agent handbook. Markdown to stdout.
    todo!("Phase 4: emit robot-docs")
}
fn gc(_args: &[String]) -> ExitCode {
    // Prune \`.doctor/runs/<id>/\` older than --before; gated on --yes.
    todo!("Phase 4: gc old run-dirs (refuses without --yes + --before)")
}
fn ls(_args: &[String]) -> ExitCode {
    // List \`.doctor/runs/\` entries.
    todo!("Phase 4: list run-dirs")
}
fn diff(_args: &[String]) -> ExitCode {
    // Show what \`--fix\` would change; read-only. Optional arg is a prior run-id/ref.
    todo!("Phase 4: show read-only fix diff")
}
RUST_EOF
}

emit_go() {
    cat <<GO_EOF
// Package doctor implements \`$tool doctor\` — self-healing diagnostics +
// fixers for $tool.
//
// SKELETON generated by scripts/scaffold-doctor.sh. Phase 4 implementer
// fills in the detector/fixer bodies; structural plumbing is already wired.
//
// Contract:
//   - 10 canonical subcommands: diagnose, fix, undo, explain, capabilities,
//     health, robot-docs, gc, ls, diff.
//   - All disk writes route through Mutate (the chokepoint).
//   - Exit codes per the canonical 11 (see RFC.md).
//   - JSON output per OUTPUT-SCHEMA.md.
//   - Universal flags include --json, --robot, --quiet, --verbose/-v,
//     --no-color, and --no-progress.
package doctor

import (
	"errors"
	"fmt"
	"os"
)

// Canonical exit codes (must match RFC.md § Section 4).
const (
	ExitSuccessOrHealthy     = 0
	ExitFindingsPresentNoFix = 1
	ExitFixPartial           = 2
	ExitFixFailedRolledBack  = 3
	ExitRefusedUnsafe        = 4
	ExitConcurrencyLost      = 5
	ExitOnlineRequired       = 6
	ExitUsageError           = 64
	ExitNoInput              = 66
	ExitCantCreate           = 73
	ExitIOError              = 74
)

// OpKind enumerates the 7 canonical Op variants. Chown is optional and not
// implemented here.
type OpKind int

const (
	OpWriteFile OpKind = iota
	OpAppendFile
	OpRename
	OpChmod
	OpSymlinkAtomic
	OpDbExec
	OpDbMigrate
)

type Op struct {
	Kind    OpKind
	Content []byte
	Mode    *uint32
	Target  string // for Rename, SymlinkAtomic
	SQL     string // for DbExec
	From    int    // for DbMigrate
	To      int    // for DbMigrate
}

// Mutate is THE CHOKEPOINT. Every disk write under '$tool doctor --fix' MUST
// go through this function. mutate-auditor (Phase 4 / Phase 7) verifies this
// invariant via static analysis.
//
// Responsibilities:
//  1. Validate op is in capabilities.allowed_ops.
//  2. Acquire per-path advisory lock (refuse with exit 5 if held > timeout).
//  3. Compute before_hash.
//  4. Backup the original verbatim to backups/.
//  5. Stage write to path.tmp.<run-id>; fsync; rename atomically; fsync parent.
//  6. Compute after_hash; append actions.jsonl line.
func Mutate(path string, op Op) error {
	return errors.New("Phase 4: implement Mutate per MUTATE-CHOKEPOINT.md")
}

// Run dispatches to a subcommand. Wire to your main() with cobra/clap-go/etc.
func Run(args []string) int {
	subcommand := "diagnose"
	if len(args) > 0 {
		subcommand = args[0]
		args = args[1:]
	}
	switch subcommand {
	case "diagnose", "":
		return diagnose(args)
	case "fix":
		return fix(args)
	case "undo":
		return undo(args)
	case "explain":
		return explain(args)
	case "capabilities":
		return capabilities(args)
	case "health":
		return health(args)
	case "robot-docs":
		return robotDocs(args)
	case "gc":
		return gc(args)
	case "ls":
		return ls(args)
	case "diff":
		return diff(args)
	default:
		fmt.Fprintf(os.Stderr, "$tool doctor: unknown subcommand %q\n", subcommand)
		return ExitUsageError
	}
}

// ---- Subcommand stubs (Phase 4 fills bodies) ----

func diagnose(args []string) int    { panic("Phase 4: implement diagnose") }
func fix(args []string) int         { panic("Phase 4: implement fix (route writes through Mutate)") }
func undo(args []string) int        { panic("Phase 4: implement undo") }
func explain(args []string) int     { panic("Phase 4: implement explain") }
func capabilities(args []string) int { panic("Phase 4: emit capabilities --json") }
func health(args []string) int      { panic("Phase 4: emit health (< 200ms target)") }
func robotDocs(args []string) int   { panic("Phase 4: emit robot-docs") }
func gc(args []string) int          { panic("Phase 4: gc (refuse without --yes + --before)") }
func ls(args []string) int          { panic("Phase 4: list run-dirs") }
func diff(args []string) int        { panic("Phase 4: show read-only fix diff") }
GO_EOF
}

emit_python() {
    cat <<PYTHON_EOF
"""$tool doctor — self-healing diagnostics + fixers for $tool.

SKELETON generated by scripts/scaffold-doctor.sh. Phase 4 implementer fills
in detector/fixer bodies; structural plumbing is already wired.

Contract:
  - 10 canonical subcommands: diagnose, fix, undo, explain, capabilities,
    health, robot-docs, gc, ls, diff.
  - All disk writes route through mutate() (the chokepoint).
  - Exit codes per the canonical 11 (see RFC.md).
  - JSON output per OUTPUT-SCHEMA.md.
  - Universal flags include --json, --robot, --quiet, --verbose/-v,
    --no-color, and --no-progress.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

# Canonical exit codes (must match RFC.md § Section 4).
EXIT_SUCCESS_OR_HEALTHY = 0
EXIT_FINDINGS_PRESENT_NO_FIX = 1
EXIT_FIX_PARTIAL = 2
EXIT_FIX_FAILED_ROLLED_BACK = 3
EXIT_REFUSED_UNSAFE = 4
EXIT_CONCURRENCY_LOST = 5
EXIT_ONLINE_REQUIRED = 6
EXIT_USAGE_ERROR = 64
EXIT_NO_INPUT = 66
EXIT_CANT_CREATE = 73
EXIT_IO_ERROR = 74


class OpKind(Enum):
    """The 7 canonical Op variants. Chown is optional, not implemented here."""
    WRITE_FILE = "WriteFile"
    APPEND_FILE = "AppendFile"
    RENAME = "Rename"
    CHMOD = "Chmod"
    SYMLINK_ATOMIC = "SymlinkAtomic"
    DB_EXEC = "DbExec"
    DB_MIGRATE = "DbMigrate"


@dataclass
class Op:
    kind: OpKind
    content: bytes | None = None
    mode: int | None = None
    target: str | None = None  # for Rename, SymlinkAtomic
    sql: str | None = None  # for DbExec
    from_version: int | None = None  # for DbMigrate
    to_version: int | None = None  # for DbMigrate


def mutate(path: Path, op: Op) -> None:
    """THE CHOKEPOINT. Every disk write under \`$tool doctor --fix\` MUST go
    through this function. mutate-auditor verifies this via static analysis.

    Responsibilities:
      1. Validate op.kind in capabilities.allowed_ops.
      2. Acquire per-path advisory lock (refuse exit 5 if held > timeout).
      3. Compute before_hash of path.
      4. Backup the original verbatim to backups/.
      5. Stage write to path.tmp.<run-id>; fsync; rename atomically; fsync parent.
      6. Compute after_hash; append actions.jsonl line.
    """
    raise NotImplementedError(
        "Phase 4: implement mutate() per MUTATE-CHOKEPOINT.md"
    )


def run_doctor(args: list[str]) -> int:
    """Top-level dispatch. Wire from your main() / argparse."""
    subcommand = args[0] if args else "diagnose"
    rest = args[1:] if len(args) > 1 else []
    dispatch = {
        "diagnose": diagnose, "": diagnose,
        "fix": fix,
        "undo": undo,
        "explain": explain,
        "capabilities": capabilities,
        "health": health,
        "robot-docs": robot_docs,
        "gc": gc,
        "ls": ls,
        "diff": diff,
    }
    handler = dispatch.get(subcommand)
    if handler is None:
        print(f"$tool doctor: unknown subcommand {subcommand!r}", file=sys.stderr)
        return EXIT_USAGE_ERROR
    return handler(rest)


# ---- Subcommand stubs (Phase 4 fills bodies) ----

def diagnose(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: implement diagnose")

def fix(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: implement fix (route writes via mutate())")

def undo(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: implement undo")

def explain(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: implement explain")

def capabilities(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: emit capabilities --json")

def health(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: emit health one-liner (< 200ms)")

def robot_docs(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: emit robot-docs")

def gc(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: gc (refuse without --yes + --before)")

def ls(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: list run-dirs")

def diff(args: list[str]) -> int:
    raise NotImplementedError("Phase 4: show read-only fix diff")
PYTHON_EOF
}

emit_typescript() {
    cat <<TS_EOF
/**
 * $tool doctor — self-healing diagnostics + fixers for $tool.
 *
 * SKELETON generated by scripts/scaffold-doctor.sh. Phase 4 implementer fills
 * in detector/fixer bodies; structural plumbing is already wired.
 *
 * Contract:
 *   - 10 canonical subcommands: diagnose, fix, undo, explain, capabilities,
 *     health, robot-docs, gc, ls, diff.
 *   - All disk writes route through mutate() (the chokepoint).
 *   - Exit codes per the canonical 11 (see RFC.md).
 *   - JSON output per OUTPUT-SCHEMA.md.
 *   - Universal flags include --json, --robot, --quiet, --verbose/-v,
 *     --no-color, and --no-progress.
 */

// Canonical exit codes (must match RFC.md § Section 4).
export const ExitCode = {
    SuccessOrHealthy: 0,
    FindingsPresentNoFix: 1,
    FixPartial: 2,
    FixFailedRolledBack: 3,
    RefusedUnsafe: 4,
    ConcurrencyLost: 5,
    OnlineRequired: 6,
    UsageError: 64,
    NoInput: 66,
    CantCreate: 73,
    IoError: 74,
} as const;

/** The 7 canonical Op variants. Chown is optional, not implemented here. */
export type Op =
    | { kind: "WriteFile"; content: Uint8Array; mode?: number }
    | { kind: "AppendFile"; content: Uint8Array }
    | { kind: "Rename"; target: string }
    | { kind: "Chmod"; mode: number }
    | { kind: "SymlinkAtomic"; target: string }
    | { kind: "DbExec"; sql: string }
    | { kind: "DbMigrate"; from: number; to: number };

/**
 * THE CHOKEPOINT. Every disk write under \`$tool doctor --fix\` MUST go
 * through this function. mutate-auditor verifies this via static analysis.
 *
 * Responsibilities:
 *   1. Validate op.kind in capabilities.allowed_ops.
 *   2. Acquire per-path advisory lock (exit 5 if held > timeout).
 *   3. Compute before_hash of path.
 *   4. Backup verbatim to backups/.
 *   5. Stage write to path.tmp.<run-id>; fsync; rename atomically; fsync parent.
 *   6. Compute after_hash; append actions.jsonl line.
 */
export async function mutate(path: string, op: Op): Promise<void> {
    throw new Error("Phase 4: implement mutate() per MUTATE-CHOKEPOINT.md");
}

/** Top-level dispatch. Wire from your main(). */
export async function runDoctor(args: string[]): Promise<number> {
    const subcommand = args[0] ?? "diagnose";
    const rest = args.slice(1);
    switch (subcommand) {
        case "diagnose":
        case "":
            return diagnose(rest);
        case "fix":
            return fix(rest);
        case "undo":
            return undo(rest);
        case "explain":
            return explain(rest);
        case "capabilities":
            return capabilities(rest);
        case "health":
            return health(rest);
        case "robot-docs":
            return robotDocs(rest);
        case "gc":
            return gc(rest);
        case "ls":
            return ls(rest);
        case "diff":
            return diff(rest);
        default:
            console.error(\`$tool doctor: unknown subcommand '\${subcommand}'\`);
            return ExitCode.UsageError;
    }
}

// ---- Subcommand stubs (Phase 4 fills bodies) ----

async function diagnose(_args: string[]): Promise<number> { throw new Error("Phase 4: implement diagnose"); }
async function fix(_args: string[]): Promise<number> { throw new Error("Phase 4: implement fix (route writes via mutate())"); }
async function undo(_args: string[]): Promise<number> { throw new Error("Phase 4: implement undo"); }
async function explain(_args: string[]): Promise<number> { throw new Error("Phase 4: implement explain"); }
async function capabilities(_args: string[]): Promise<number> { throw new Error("Phase 4: emit capabilities --json"); }
async function health(_args: string[]): Promise<number> { throw new Error("Phase 4: emit health one-liner (< 200ms)"); }
async function robotDocs(_args: string[]): Promise<number> { throw new Error("Phase 4: emit robot-docs"); }
async function gc(_args: string[]): Promise<number> { throw new Error("Phase 4: gc (refuse without --yes + --before)"); }
async function ls(_args: string[]): Promise<number> { throw new Error("Phase 4: list run-dirs"); }
async function diff(_args: string[]): Promise<number> { throw new Error("Phase 4: show read-only fix diff"); }
TS_EOF
}

# Write the file.
case "$language" in
    rust)       emit_rust >       "$out_path" ;;
    go)         emit_go   >       "$out_path" ;;
    python)     emit_python >     "$out_path" ;;
    typescript) emit_typescript > "$out_path" ;;
esac

echo "scaffold-doctor: wrote $language stub to $out_path" >&2
echo "{\"language\":\"$language\",\"out_path\":\"$out_path\",\"tool\":\"$tool\"}"
