#!/usr/bin/env bash
# cargo-tree-soundness.sh — flag deps whose unsafe is reachable through this project's pub API
# Usage: ./cargo-tree-soundness.sh <project> <audit-dir>

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Sourced through runtime SCRIPT_DIR.
# shellcheck disable=SC1091
. "$SCRIPT_DIR/audit-dir-guard.sh"

PROJECT="${1:?usage: cargo-tree-soundness.sh <project> <audit-dir>}"
AUDIT_DIR="${2:?usage: cargo-tree-soundness.sh <project> <audit-dir>}"
PROJECT=$(audit_realpath "$PROJECT")
AUDIT_DIR=$(audit_require_under_project "$AUDIT_DIR" "$PROJECT")

mkdir -p "$AUDIT_DIR/phase1"
cd "$PROJECT"

cargo tree --all-features > "$AUDIT_DIR/phase1/cargo-tree.txt"

OUT="$AUDIT_DIR/phase1/cargo-tree-soundness.md"

# Probe for cargo-geiger up-front. Without it, every dep's COUNT is 0 and the
# "Deps with geiger count > 0" section is empty — which a reader can easily
# mistake for "no deps have unsafe." Emit a clearly-flagged DEGRADED status
# instead.
HAVE_GEIGER=false
if command -v cargo-geiger >/dev/null 2>&1 \
   || cargo +nightly geiger --version >/dev/null 2>&1; then
  HAVE_GEIGER=true
fi

if ! $HAVE_GEIGER; then
  cat > "$OUT" <<EOF
# Cargo tree soundness analysis

Generated by cargo-tree-soundness.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).

## Status: DEGRADED — cargo-geiger not installed

This analysis depends on \`cargo +nightly geiger\` to enumerate per-dep unsafe counts.
Without geiger, this script CANNOT distinguish "no deps have unsafe" from
"we couldn't measure." In \`dependency-soundness\` / \`forbid-soundness\` mode
this is the headline artifact, so a degraded run materially weakens the audit.

### Install

\`\`\`bash
cargo +nightly install --locked cargo-geiger
\`\`\`

Then re-run:

\`\`\`bash
$(printf '%q ' "$0" "$PROJECT" "$AUDIT_DIR")
\`\`\`

### What this script would have produced

For each direct dependency: a row with the count of in-use unsafe expressions,
plus a NEEDS-INVESTIGATION marker for the Phase 3 synthesizer.

### Available without geiger

- \`$AUDIT_DIR/phase1/cargo-tree.txt\` — full dep graph (already written)
- Phase 3 synthesis can still write a class-based ("heavy / moderate / minimal")
  characterization from ecosystem knowledge, but it cannot be numerically grounded.

EOF
  echo "DEGRADED: cargo-geiger not installed; wrote degraded status to $OUT" >&2
  echo "Wrote $OUT (degraded)"
  exit 3
fi

cat > "$OUT" <<EOF
# Cargo tree soundness analysis

Generated by cargo-tree-soundness.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).

## Deps with geiger count > 0

EOF

# Per direct dep, fetch its geiger count.
DEPS=$(cargo metadata --format-version 1 2>/dev/null | jq -r '.packages[] | select(.name != null) | .name' | sort -u)
DEPS_WITH_UNSAFE=0

for dep in $DEPS; do
  COUNT=$(cargo +nightly geiger -p "$dep" --output-format Json 2>/dev/null | \
          jq '[.packages[]?.package.metrics.counters | objects | .[] | numbers] | add // 0' \
          2>/dev/null || echo 0)
  # Normalize: jq null → 0; empty → 0
  case "$COUNT" in ''|null) COUNT=0 ;; esac
  # Numeric guard — avoid bash "integer expression expected" leaks
  if [[ "$COUNT" =~ ^[0-9]+$ ]] && [ "$COUNT" -gt 0 ]; then
    DEPS_WITH_UNSAFE=$((DEPS_WITH_UNSAFE + 1))
    {
      echo "### $dep"
      echo "Geiger count: $COUNT"
      echo ""
      echo "Reachability from this project's pub API: NEEDS-INVESTIGATION"
      echo "(rustdoc JSON cross-reference required to determine)"
      echo ""
    } >> "$OUT"
  fi
done

# If the loop ran but found zero deps with unsafe, say so explicitly — readers
# of an empty section can't tell "nothing to report" from "tool failed."
if [ "$DEPS_WITH_UNSAFE" -eq 0 ]; then
  cat >> "$OUT" <<EOF
_No direct dependency has used-unsafe > 0 according to \`cargo +nightly geiger\`.
This is rare — the empty result was verified rather than tool-failure (geiger
was present and ran successfully against every dep). Treat with the same
scepticism as any other numerical claim: re-running on a fresh \`cargo clean\`
build should reproduce it._
EOF
fi

cat >> "$OUT" <<EOF

## Action items

For each dep listed above, the Phase 3 synthesizer must:
1. Walk this project's pub API.
2. Determine which dep API surfaces are reached.
3. Determine whether those dep API surfaces internally invoke the dep's unsafe.
4. If yes — the dep's unsafe is on this project's soundness surface; consider:
   (a) wrap the dep's API in a stricter project-side abstraction, or
   (b) replace the dep with a less-unsafe alternative, or
   (c) file upstream issue / PR with the dep, or
   (d) document the inherited soundness obligation in this project's docs.
EOF

echo "Wrote $OUT ($DEPS_WITH_UNSAFE deps with used-unsafe > 0)"
