#!/usr/bin/env bash
# publish-cargo-vet-certs.sh — convert dep-soundness audit findings into
# cargo-vet certifications.
#
# After dependency-soundness mode produces audit/synthesis/dep-soundness.md
# with verdicts per dep (audited / unaudited / fails-soundness), this script
# emits a sequence of `cargo vet certify` commands for the deps the audit
# certifies. The user reviews + runs them inside their project repo to push
# the certifications upstream (cargo-vet ecosystem).
#
# Usage:
#   publish-cargo-vet-certs.sh <audit-dir>
#
# Output:
#   <audit-dir>/cargo-vet-certs.sh — a reviewable script of cargo-vet commands.
#   Prints a summary of how many deps would be certified vs flagged.

set -euo pipefail

AUDIT_DIR="${1:?usage: publish-cargo-vet-certs.sh <audit-dir>}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/audit-dir-guard.sh"
AUDIT_DIR=$(audit_realpath "$AUDIT_DIR")
PROJECT_ROOT=$(audit_project_root_from_dir "$AUDIT_DIR")
AUDIT_DIR=$(audit_require_under_project "$AUDIT_DIR" "$PROJECT_ROOT")
SOUNDNESS_DOC="$AUDIT_DIR/audit/synthesis/dep-soundness.md"
OUT="$AUDIT_DIR/cargo-vet-certs.sh"

if [ ! -f "$SOUNDNESS_DOC" ]; then
  echo "error: $SOUNDNESS_DOC not found" >&2
  echo "       run dependency-soundness mode first, or create the dep-soundness.md by hand" >&2
  exit 1
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "warning: cargo not on PATH; emitting commands anyway" >&2
fi

# Parse dep-soundness.md. Format expected (per DEP-SOUNDNESS-PROTOCOL.md):
#
#   ## <dep-name> (geiger: <N>)
#   ...
#   ### Soundness verdict
#   - <body — verdict text>
#
# We extract (dep-name, verdict-text) pairs. A "certifiable" verdict matches:
# - "All proof obligations enforced"
# - "No bypass paths"
# - "Sound"
# A "flag" verdict matches:
# - "fails-soundness"
# - "TODO"
# - "unaudited"

cat > "$OUT" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by publish-cargo-vet-certs.sh from the audit's dep-soundness findings.
# Review every certification before running. Each line corresponds to a single
# (dep, version) pair the audit found sound for our project's usage.
#
# IMPORTANT: cargo-vet certifications encode YOUR project's review of the dep
# for YOUR usage. They are not blanket assertions about the dep. Run from your
# project's repo (where Cargo.lock lives), not the audit dir.
#
# Usage:
#   cd <project>
#   bash <audit-dir>/cargo-vet-certs.sh

set -euo pipefail

if [ ! -f Cargo.lock ]; then
  echo "error: Cargo.lock not found; run from your project root" >&2
  exit 1
fi

if ! command -v cargo-vet >/dev/null 2>&1; then
  echo "error: cargo-vet not installed" >&2
  echo "  install: cargo install cargo-vet" >&2
  exit 1
fi

# Ensure cargo-vet is initialized
if [ ! -d supply-chain ]; then
  echo "==> initializing cargo-vet (one-time)"
  cargo vet init
fi

EOF
chmod +x "$OUT"

certified=0
flagged=0
deps_cert=()
deps_flag=()

current_dep=""
current_geiger=""
verdict_seen=0

while IFS= read -r line; do
  # New dep section
  if [[ "$line" =~ ^##\ ([a-zA-Z0-9_-]+)\ \(geiger:\ ([0-9]+)\) ]]; then
    current_dep="${BASH_REMATCH[1]}"
    current_geiger="${BASH_REMATCH[2]}"
    verdict_seen=0
    continue
  fi
  # Verdict header
  if [[ "$line" =~ ^###\ Soundness\ verdict ]]; then
    verdict_seen=1
    continue
  fi
  # Verdict bullet (first bullet after the verdict header)
  if [ "$verdict_seen" = "1" ] && [[ "$line" =~ ^-\  ]]; then
    verdict="${line#- }"
    verdict_seen=0  # only consume one verdict bullet per section
    if echo "$verdict" | grep -qiE 'all proof obligations enforced|no bypass paths|verified sound|sound$'; then
      certified=$((certified + 1))
      deps_cert+=("$current_dep")
      echo "# $current_dep (geiger: $current_geiger) — $verdict" >> "$OUT"
      echo "cargo vet certify '$current_dep' --criteria safe-to-deploy || \\" >> "$OUT"
      echo "  echo \"  skipped: cargo-vet certify failed for $current_dep — review manually\"" >> "$OUT"
      echo "" >> "$OUT"
    elif echo "$verdict" | grep -qiE 'fails-soundness|todo|unaudited|needs.investigation'; then
      flagged=$((flagged + 1))
      deps_flag+=("$current_dep")
      echo "# $current_dep (geiger: $current_geiger) — FLAGGED: $verdict" >> "$OUT"
      echo "#   (no certification emitted; needs follow-up)" >> "$OUT"
      echo "" >> "$OUT"
    fi
    continue
  fi
done < "$SOUNDNESS_DOC"

cat >> "$OUT" <<'EOF'

echo
echo "==> Done. Review supply-chain/audits.toml to see the certifications added."
echo "    Commit + push: 'git add supply-chain/ && git commit -m \"vet: certify audited deps\"'"
EOF

echo "Wrote $OUT"
echo "Certifications: $certified deps"
echo "Flagged (needs review): $flagged deps"
if [ "${#deps_cert[@]}" -gt 0 ]; then
  echo "  Certified:"
  printf '    - %s\n' "${deps_cert[@]}"
fi
if [ "${#deps_flag[@]}" -gt 0 ]; then
  echo "  Flagged:"
  printf '    - %s\n' "${deps_flag[@]}"
fi
