module.exports = {
  apps: [
    {
      name: "better-ccflare",
      script: "cmd.exe",
      args: "/c cd /d C:\\WORK\\better-ccflare && apps\\cli\\dist\\better-ccflare-windows-x64.exe --serve --port 4800",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "512M",
      error_file: "/c/users/oystein/.config/pm2/logs/better-ccflare-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/better-ccflare-out.log",
      merge_logs: true,
    },
    {
      name: "pal-mcp",
      cwd: "/c/WORK/pal-mcp-server",
      script: "server.py",
      interpreter: "/c/WORK/pal-mcp-server/.pal_venv/bin/python",
      env: { MCP_TRANSPORT: "sse", MCP_PORT: "4801" },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "1G",
      error_file: "/c/users/oystein/.config/pm2/logs/pal-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/pal-mcp-out.log",
      merge_logs: true,
    },
    {
      name: "google-workspace-mcp",
      script: "npx",
      args: "-y supergateway --stdio \"npx -y @presto-ai/google-workspace-mcp\" --port 4802",
      env: { DISPLAY: ":0" },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "512M",
      error_file: "/c/users/oystein/.config/pm2/logs/google-workspace-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/google-workspace-out.log",
      merge_logs: true,
    },
  ],
};
