module.exports = {
  apps: [
    {
      name: "better-ccflare",
      script: "cmd.exe",
      args: "/c cd /d C:\\WORK\\better-ccflare && apps\\cli\\dist\\better-ccflare-windows-x64.exe --serve --port 4800",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "512M",
      error_file: "/c/users/oystein/.config/pm2/logs/better-ccflare-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/better-ccflare-out.log",
      merge_logs: true,
    },
    {
      name: "pal-mcp",
      cwd: "/c/WORK/pal-mcp-server",
      script: "server.py",
      interpreter: "/c/WORK/pal-mcp-server/.pal_venv/bin/python",
      env: { MCP_TRANSPORT: "sse", MCP_PORT: "4801" },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "1G",
      error_file: "/c/users/oystein/.config/pm2/logs/pal-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/pal-mcp-out.log",
      merge_logs: true,
    },
    {
      name: "google-workspace-mcp",
      script: "/c/users/oystein/.local/bin/uvx",
      args: "workspace-mcp --transport streamable-http --single-user",
      interpreter: "none",
      env: {
        WORKSPACE_MCP_PORT: "4802",
        DISPLAY: ":0",
        OAUTHLIB_INSECURE_TRANSPORT: "1",
        GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
        GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "512M",
      error_file: "/c/users/oystein/.config/pm2/logs/google-workspace-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/google-workspace-out.log",
      merge_logs: true,
    },
  ],
};
