module.exports = {
  apps: [
    {
      name: "better-ccflare",
      script: "cmd.exe",
      args: "/c cd /d C:\\WORK\\better-ccflare && apps\\cli\\dist\\better-ccflare-windows-x64.exe --serve --port 4800",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "512M",
      error_file: "/c/users/oystein/.config/pm2/logs/better-ccflare-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/better-ccflare-out.log",
      merge_logs: true,
    },
    {
      name: "pal-mcp",
      cwd: "/c/WORK/pal-mcp-server",
      script: "server.py",
      interpreter: "/c/WORK/pal-mcp-server/.pal_venv/bin/python",
      env: { MCP_TRANSPORT: "sse", MCP_PORT: "4801" },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "1G",
      error_file: "/c/users/oystein/.config/pm2/logs/pal-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/pal-mcp-out.log",
      merge_logs: true,
    },
    {
      name: "google-workspace-mcp",
      script: "/c/users/oystein/.local/bin/uvx",
      args: "workspace-mcp --transport streamable-http --single-user",
      interpreter: "none",
      env: {
        WORKSPACE_MCP_PORT: "4802",
        DISPLAY: ":0",
        OAUTHLIB_INSECURE_TRANSPORT: "1",
        GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
        GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "512M",
      error_file: "/c/users/oystein/.config/pm2/logs/google-workspace-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/google-workspace-out.log",
      merge_logs: true,
    },
    {
      name: "slack-mcp",
      script: "supergateway",
      args: "--stdio /c/users/oystein/bin/slack-mcp --outputTransport streamableHttp --port 4803",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "256M",
      error_file: "/c/users/oystein/.config/pm2/logs/slack-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/slack-mcp-out.log",
      merge_logs: true,
    },
    {
      name: "sentry-mcp",
      script: "supergateway",
      args: "--stdio /c/users/oystein/bin/sentry-mcp --outputTransport streamableHttp --port 4804",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "256M",
      error_file: "/c/users/oystein/.config/pm2/logs/sentry-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/sentry-mcp-out.log",
      merge_logs: true,
    },
    {
      name: "hubspot-mcp",
      script: "supergateway",
      args: "--stdio /c/users/oystein/bin/hubspot-mcp --outputTransport streamableHttp --port 4805",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "256M",
      error_file: "/c/users/oystein/.config/pm2/logs/hubspot-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/hubspot-mcp-out.log",
      merge_logs: true,
    },
    {
      name: "zendesk-mcp",
      script: "supergateway",
      args: "--stdio /c/users/oystein/bin/zendesk-mcp --outputTransport streamableHttp --port 4806",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "256M",
      error_file: "/c/users/oystein/.config/pm2/logs/zendesk-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/zendesk-mcp-out.log",
      merge_logs: true,
    },
    {
      name: "apify-mcp",
      script: "supergateway",
      args: "--stdio /c/users/oystein/bin/apify-mcp --outputTransport streamableHttp --port 4807",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "256M",
      error_file: "/c/users/oystein/.config/pm2/logs/apify-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/apify-mcp-out.log",
      merge_logs: true,
    },
    {
      name: "atlassian-mcp",
      script: "supergateway",
      args: "--stdio 'npx -y mcp-remote https://mcp.atlassian.com/v1/mcp' --outputTransport streamableHttp --port 4808",
      interpreter: "none",
      env: {},
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      max_memory_restart: "256M",
      error_file: "/c/users/oystein/.config/pm2/logs/atlassian-mcp-error.log",
      out_file: "/c/users/oystein/.config/pm2/logs/atlassian-mcp-out.log",
      merge_logs: true,
    },
  ],
};
