#!/usr/bin/env bash
# scripts/gauntlet-status.sh — terminal-native dashboard snapshot of a gauntlet workspace.
#
# Reads durable state from <workspace>/{reports/convergence_tracker.json, reports/, .gauntlet/, ...}
# and prints a 30-line snapshot. The artifact files are the source of truth; this script
# just renders.
#
# Usage:
#   gauntlet-status.sh <workspace>                 # text snapshot (default)
#   gauntlet-status.sh <workspace> --markdown      # markdown form (for STATUS.md regen)
#   gauntlet-status.sh <workspace> --json          # JSON form (for downstream tooling)
#
# Exit codes:
#   0 = snapshot rendered
#   2 = bad arguments
#   3 = workspace initialized but convergence tracker not generated yet
#
# Per references/methodology/MONITORING-AND-DASHBOARDS.md § Layer A.

set -euo pipefail

usage() {
  cat <<'EOF'
gauntlet-status.sh — terminal-native snapshot of a gauntlet workspace.

Usage:
  gauntlet-status.sh <workspace>             # text (default)
  gauntlet-status.sh <workspace> --markdown  # markdown (for STATUS.md regen)
  gauntlet-status.sh <workspace> --json      # JSON (for downstream tooling)
EOF
  exit "${1:-2}"
}

[ $# -lt 1 ] && usage 2
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage 0
fi

WORKSPACE="$1"
MODE="${2:-text}"
LIVE_PROBES="${GAUNTLET_STATUS_LIVE_PROBES:-0}"

[ -d "$WORKSPACE" ] || { echo "ERROR: workspace dir not found: $WORKSPACE" >&2; exit 2; }
TRACKER="$WORKSPACE/reports/convergence_tracker.json"
if [ ! -f "$TRACKER" ] && [ -f "$WORKSPACE/convergence_tracker.json" ]; then
  TRACKER="$WORKSPACE/convergence_tracker.json"
fi
if [ ! -f "$TRACKER" ]; then
  # The convergence tracker is written by convergence-tracker.sh during Phase 11.
  # Earlier workspaces are initialized but have no generated convergence state yet.
  # Emit a concrete next-step message instead of implying Phase 0 failed.
  if [ -f "$WORKSPACE/phase0_workspace_init.md" ]; then
    cat >&2 <<EOF
NOTE: workspace is initialized but no reports/convergence_tracker.json yet.
The tracker is generated by scripts/convergence-tracker.sh during Phase 11.
The workspace is currently in pre-Phase-11 tracker state.

Phase 0 init artifact: $WORKSPACE/phase0_workspace_init.md
Phase 0 project class: $WORKSPACE/phase0_project_class.json

Continue through contracts, oracle/perf/conformance harness build, Phase 9 baseline, Phase 10 ideas, then Phase 11 convergence tracking.
EOF
    exit 3
  fi
  echo "ERROR: workspace not initialized; run init-workspace.sh first" >&2
  echo "       (missing $WORKSPACE/phase0_workspace_init.md AND $WORKSPACE/reports/convergence_tracker.json)" >&2
  exit 3
fi
command -v jq >/dev/null 2>&1 || { echo "ERROR: jq not installed; apt install jq (or brew install jq)" >&2; exit 4; }

# Helper: safe jq read with fallback.
j() { jq -r "$1" "$2" 2>/dev/null || echo "?"; }

# --- Read state ---
PHASE=$(j '.current_phase // 11' "$TRACKER")
ROUND=$(j '.current_round // .round_count // "?"' "$TRACKER")
CLEAN=$(j '.consecutive_clean_rounds // (if .clean_last_two then (.required_consecutive_clean // 2) else 0 end)' "$TRACKER")
CONVERGED=$(j '.converged // false' "$TRACKER")
LAST_TWO=$(jq -c '.last_two_findings // []' "$TRACKER" 2>/dev/null || echo '[]')
TIER=$(j '.tier // "unknown"' "$TRACKER")
RUN_ID=$(j '.run_id // (.workspace | split("/")[-1]) // "unknown"' "$TRACKER")
OPEN_TOTAL=$(j '.by_pillar_open.total // .open_hypothesis_count // "?"' "$TRACKER")
OPEN_PERF=$(j '.by_pillar_open.perf // .by_pillar_open.performance // "?"' "$TRACKER")
OPEN_CONFORM=$(j '.by_pillar_open.conformance // "?"' "$TRACKER")
OPEN_SURF=$(j '.by_pillar_open.surface // .by_pillar_open.surface_parity // "?"' "$TRACKER")
LAST_UPDATE=$(j '.last_update_utc // .generated_at // "?"' "$TRACKER")
if [ "$OPEN_PERF" = "?" ] && [ "$OPEN_CONFORM" = "?" ] && [ "$OPEN_SURF" = "?" ]; then
  OPEN_PERF="$OPEN_TOTAL"
  OPEN_CONFORM="$OPEN_TOTAL"
  OPEN_SURF="$OPEN_TOTAL"
fi

RATCHET="$WORKSPACE/reports/ratchet_state.json"
RATCHET_DECISION="$WORKSPACE/reports/ratchet_decision.json"
# Two schemas to support:
#  - per-pillar: { "perf": {"decision":..., "lower_bound":...}, "conformance":..., "surface":... }
#  - flat (current apply-ratchet.sh output): { "global_lower":..., "schema_version":..., ... }
# The flat form pairs with ratchet_decision.json for the .decision field.
if [ -f "$RATCHET" ]; then
  RATCHET_PERF=$(j '.perf.decision' "$RATCHET")
  RATCHET_CONFORM=$(j '.conformance.decision' "$RATCHET")
  RATCHET_SURF=$(j '.surface.decision' "$RATCHET")
  LOWER_PERF=$(j '.perf.lower_bound' "$RATCHET")
  LOWER_CONFORM=$(j '.conformance.lower_bound' "$RATCHET")
  LOWER_SURF=$(j '.surface.lower_bound' "$RATCHET")
  # If per-pillar shape returned all-null-or-?, fall back to the flat-schema reading.
  # The `j` helper returns the literal string "null" when jq succeeds but the
  # field is absent (jq's default), or "?" when jq itself fails.
  is_empty() { [ "$1" = "null" ] || [ "$1" = "?" ] || [ -z "$1" ]; }
  if is_empty "$RATCHET_PERF" && is_empty "$RATCHET_CONFORM" && is_empty "$RATCHET_SURF"; then
    GLOBAL_LOWER=$(j '.global_lower' "$RATCHET")
    GLOBAL_DECISION="?"
    if [ -f "$RATCHET_DECISION" ]; then
      GLOBAL_DECISION=$(j '.decision' "$RATCHET_DECISION")
    fi
    RATCHET_PERF="$GLOBAL_DECISION (global)"
    RATCHET_CONFORM="$GLOBAL_DECISION (global)"
    RATCHET_SURF="$GLOBAL_DECISION (global)"
    LOWER_PERF="$GLOBAL_LOWER (global)"
    LOWER_CONFORM="$GLOBAL_LOWER (global)"
    LOWER_SURF="$GLOBAL_LOWER (global)"
  fi
else
  RATCHET_PERF="(not yet baselined)"
  RATCHET_CONFORM="(not yet baselined)"
  RATCHET_SURF="(not yet baselined)"
  LOWER_PERF="?"
  LOWER_CONFORM="?"
  LOWER_SURF="?"
fi

# Active NTM session (best-effort; the workspace's basename is the convention).
# All best-effort lookups use `|| true` to keep set -euo pipefail from killing the script
# on tool-not-installed or unexpected-output paths.
WS_BASENAME=$(basename "$WORKSPACE")
NTM_ACTIVE="(live probe skipped)"
if [ "$LIVE_PROBES" = "1" ] && command -v ntm >/dev/null 2>&1; then
  NTM_SNAP=$(timeout -k 1s 2s ntm --robot-snapshot --robot-format=json 2>/dev/null || echo '{}')
  NTM_LOOKUP=$(echo "$NTM_SNAP" | jq -r --arg n "$WS_BASENAME" \
    '.sessions[]? | select(.name == $n) | .pane_count' 2>/dev/null | head -1 || true)
  [ -n "$NTM_LOOKUP" ] && NTM_ACTIVE="$NTM_LOOKUP"
fi

# Active rch jobs (best-effort).
RCH_JOBS="(live probe skipped)"
if [ "$LIVE_PROBES" = "1" ] && command -v rch >/dev/null 2>&1; then
  RCH_LOOKUP=$(timeout -k 1s 2s rch jobs --json 2>/dev/null | jq -r --arg ws "$WORKSPACE" \
    '[.jobs[]? | select((.cwd // "") == $ws or ((.args // [] | tostring) | contains($ws)))] | length' 2>/dev/null || true)
  [ -n "$RCH_LOOKUP" ] && RCH_JOBS="$RCH_LOOKUP"
fi

# Last commit + last failure heuristic (best-effort).
LAST_COMMIT="?"
if git -C "$WORKSPACE" rev-parse --git-dir >/dev/null 2>&1; then
  LAST_COMMIT=$(git -C "$WORKSPACE" log -1 --pretty='%cr — %s' 2>/dev/null || echo "?")
fi

# Look for the most-recent failure bundle.
LAST_FAILURE=""
LATEST_BUNDLE=$(find "$WORKSPACE" -name 'bundle.json' -path '*/failures/*' -printf '%T@ %p\n' 2>/dev/null \
  | sort -rn | head -1 | awk '{print $2}')
if [ -n "$LATEST_BUNDLE" ]; then
  BUNDLE_AGE=$(stat -c %Y "$LATEST_BUNDLE" 2>/dev/null || echo 0)
  NOW=$(date +%s)
  AGE_MIN=$(( (NOW - BUNDLE_AGE) / 60 ))
  LAST_FAILURE="${AGE_MIN}m ago — $(basename "$(dirname "$LATEST_BUNDLE")")"
fi

# Next-action heuristic (cheap; the orchestrator owns the real decision).
NEXT_ACTION="(consult orchestrator)"
case "$PHASE" in
  0|1|2|3|4|5|6|7|8) NEXT_ACTION="Phase $PHASE in progress; continue to Phase $((PHASE+1)) when exit-criteria met (see methodology/DEFINITION-OF-DONE.md)" ;;
  9) NEXT_ACTION="Phase 9 baseline; if green, advance to Phase 10 (idea-wizard)" ;;
  10) NEXT_ACTION="Phase 10 idea-wizard done; advance to Phase 11 (iterate)" ;;
  11)
    if [ "$CONVERGED" = "true" ]; then
      NEXT_ACTION="Phase 11 converged; advance to Phase 12"
    else
      NEXT_ACTION="Phase 11 round_count=$ROUND; dispatch next round (last_two_findings=$LAST_TWO, open_hypotheses=$OPEN_TOTAL)"
    fi
    ;;
  12) NEXT_ACTION="Phase 12 remediation design; advance to Phase 13 when scored" ;;
  13) NEXT_ACTION="Phase 13 beads handoff; advance to Phase 14 when graph clean" ;;
  14) NEXT_ACTION="Phase 14 fresh-eyes; advance to Phase 15 when 2 consecutive clean rounds" ;;
  15) NEXT_ACTION="Phase 15 soak; advance to Phase 16 when no findings" ;;
  16) NEXT_ACTION="Phase 16 final artifacts; check certification_bundle/release_certificate.json" ;;
esac

# --- Emit ---
emit_text() {
  cat <<EOF
Gauntlet: $WS_BASENAME
Run-id:   $RUN_ID
Tier:     $TIER
Phase:    $PHASE (round_count $ROUND; clean_last_two_equivalent = $CLEAN; converged = $CONVERGED)

Pillars:
  perf:        ratchet=$RATCHET_PERF    conformal_lower=$LOWER_PERF    open_hypotheses=$OPEN_PERF
  conformance: ratchet=$RATCHET_CONFORM conformal_lower=$LOWER_CONFORM open_hypotheses=$OPEN_CONFORM
  surface:     ratchet=$RATCHET_SURF    conformal_lower=$LOWER_SURF    open_hypotheses=$OPEN_SURF

Active NTM session: $NTM_ACTIVE
Active rch jobs:    $RCH_JOBS
Last commit:        $LAST_COMMIT
${LAST_FAILURE:+Last failure:       $LAST_FAILURE}
Last tracker update: $LAST_UPDATE

Next action: $NEXT_ACTION
EOF
}

emit_markdown() {
  cat <<EOF
# Gauntlet Status — $WS_BASENAME

**Run-id:** $RUN_ID
**Tier:** $TIER
**Phase:** $PHASE (round_count $ROUND; clean_last_two_equivalent = $CLEAN; converged = $CONVERGED)
**Last tracker update:** $LAST_UPDATE

## Pillars

| Pillar | Ratchet | Conformal lower | Open hypotheses |
|---|---|---|---|
| perf | $RATCHET_PERF | $LOWER_PERF | $OPEN_PERF |
| conformance | $RATCHET_CONFORM | $LOWER_CONFORM | $OPEN_CONFORM |
| surface | $RATCHET_SURF | $LOWER_SURF | $OPEN_SURF |

## Live state

- **Active NTM session:** $NTM_ACTIVE
- **Active rch jobs:** $RCH_JOBS
- **Last commit:** $LAST_COMMIT
${LAST_FAILURE:+- **Last failure:** $LAST_FAILURE}

## Next action

$NEXT_ACTION
EOF
}

emit_json() {
  jq -n \
    --arg ws "$WS_BASENAME" \
    --arg run_id "$RUN_ID" \
    --arg tier "$TIER" \
    --arg phase "$PHASE" \
    --arg round "$ROUND" \
    --arg clean "$CLEAN" \
    --arg converged "$CONVERGED" \
    --argjson last_two "$LAST_TWO" \
    --arg ratchet_perf "$RATCHET_PERF" \
    --arg ratchet_conf "$RATCHET_CONFORM" \
    --arg ratchet_surf "$RATCHET_SURF" \
    --arg lower_perf "$LOWER_PERF" \
    --arg lower_conf "$LOWER_CONFORM" \
    --arg lower_surf "$LOWER_SURF" \
    --arg open_perf "$OPEN_PERF" \
    --arg open_conf "$OPEN_CONFORM" \
    --arg open_surf "$OPEN_SURF" \
    --arg ntm "$NTM_ACTIVE" \
    --arg rch "$RCH_JOBS" \
    --arg last_commit "$LAST_COMMIT" \
    --arg last_failure "$LAST_FAILURE" \
    --arg last_update "$LAST_UPDATE" \
    --arg next "$NEXT_ACTION" \
    '{
      workspace: $ws, run_id: $run_id, tier: $tier,
      phase: ($phase | tonumber? // $phase),
      round: ($round | tonumber? // $round),
      clean_last_two_equivalent: ($clean | tonumber? // $clean),
      last_two_findings: $last_two,
      converged: ($converged == "true"),
      pillars: {
        perf:        {ratchet: $ratchet_perf, conformal_lower: ($lower_perf | tonumber? // $lower_perf), open_hypotheses: ($open_perf | tonumber? // $open_perf)},
        conformance: {ratchet: $ratchet_conf, conformal_lower: ($lower_conf | tonumber? // $lower_conf), open_hypotheses: ($open_conf | tonumber? // $open_conf)},
        surface:     {ratchet: $ratchet_surf, conformal_lower: ($lower_surf | tonumber? // $lower_surf), open_hypotheses: ($open_surf | tonumber? // $open_surf)}
      },
      live: {
        ntm_session: $ntm,
        rch_jobs: ($rch | tonumber? // $rch),
        last_commit: $last_commit,
        last_failure: $last_failure,
        last_tracker_update: $last_update
      },
      next_action: $next
    }'
}

case "$MODE" in
  text|--text)         emit_text ;;
  markdown|--markdown) emit_markdown ;;
  json|--json)         emit_json ;;
  *) echo "ERROR: unknown mode '$MODE'; use text|markdown|json" >&2; exit 2 ;;
esac
