-- Built-in color scheme names, dark ones first. Generated from the fork's
-- frankenterm/config/src/scheme_data.rs (the Lua API has no list function).
return {
  dark = {
    "3024 (base16)",
    "3024 (dark) (terminal.sexy)",
    "3024 Night",
    "3024 Night (Gogh)",
    "Aardvark Blue",
    "Abernathy",
    "Aci (Gogh)",
    "Aco (Gogh)",
    "Adventure",
    "Adventure Time (Gogh)",
    "AdventureTime",
    "Afterglow",
    "Afterglow (Gogh)",
    "Alien Blood (Gogh)",
    "AlienBlood",
    "Andromeda",
    "Apathy (base16)",
    "Apple Classic",
    "Apple System Colors",
    "Apprentice (base16)",
    "Apprentice (Gogh)",
    "arcoiris",
    "Argonaut",
    "Argonaut (Gogh)",
    "Arthur",
    "Arthur (Gogh)",
    "Ashes (base16)",
    "Ashes (dark) (terminal.sexy)",
    "Astrodark (Gogh)",
    "astromouse (terminal.sexy)",
    "Atelier Cave (base16)",
    "Atelier Dune (base16)",
    "Atelier Estuary (base16)",
    "Atelier Forest (base16)",
    "Atelier Heath (base16)",
    "Atelier Lakeside (base16)",
    "Atelier Plateau (base16)",
    "Atelier Savanna (base16)",
    "Atelier Seaside (base16)",
    "Atelier Sulphurpool (base16)",
    "Atelierdune (dark) (terminal.sexy)",
    "Atelierforest (dark) (terminal.sexy)",
    "Atelierheath (dark) (terminal.sexy)",
    "Atelierlakeside (dark) (terminal.sexy)",
    "Atelierseaside (dark) (terminal.sexy)",
    "AtelierSulphurpool",
    "Atlas (base16)",
    "Atom",
    "Atom (Gogh)",
    "Aura (Gogh)",
    "Aurora",
    "ayu",
    "Ayu Dark (Gogh)",
    "Ayu Mirage",
    "Ayu Mirage (Gogh)",
    "Azu (Gogh)",
    "Bamboo",
    "Bamboo Multiplex",
    "Banana Blueberry",
    "Batman",
    "Belafonte Night",
    "Belafonte Night (Gogh)",
    "Belge (terminal.sexy)",
    "Bespin (base16)",
    "Bespin (dark) (terminal.sexy)",
    "Bim (Gogh)",
    "Birds Of Paradise (Gogh)",
    "BirdsOfParadise",
    "Bitmute (terminal.sexy)",
    "Black Metal (base16)",
    "Black Metal (Bathory) (base16)",
    "Black Metal (Burzum) (base16)",
    "Black Metal (Dark Funeral) (base16)",
    "Black Metal (Gorgoroth) (base16)",
    "Black Metal (Immortal) (base16)",
    "Black Metal (Khold) (base16)",
    "Black Metal (Marduk) (base16)",
    "Black Metal (Mayhem) (base16)",
    "Black Metal (Nile) (base16)",
    "Black Metal (Venom) (base16)",
    "Blazer",
    "Blazer (Gogh)",
    "Bleh-1 (terminal.sexy)",
    "Blue Dolphin (Gogh)",
    "Blue Matrix",
    "BlueBerryPie",
    "BlueDolphin",
    "BlulocoDark",
    "Borland",
    "Borland (Gogh)",
    "Breath (Gogh)",
    "Breath Darker (Gogh)",
    "Breath Silverfox (Gogh)",
    "Breeze",
    "Breeze (Gogh)",
    "Brewer (base16)",
    "Brewer (dark) (terminal.sexy)",
    "Bright (base16)",
    "Bright Lights",
    "Broadcast",
    "Broadcast (Gogh)",
    "Brogrammer",
    "Brogrammer (base16)",
    "Brogrammer (Gogh)",
    "Brush Trees Dark (base16)",
    "Builtin Dark",
    "Builtin Pastel Dark",
    "Builtin Solarized Dark",
    "Builtin Tango Dark",
    "Butrin (Gogh)",
    "C64",
    "C64 (Gogh)",
    "Cai (Gogh)",
    "Calamity",
    "Campbell (Gogh)",
    "Canvased Pastel (terminal.sexy)",
    "carbonfox",
    "Catch Me If You Can (terminal.sexy)",
    "Catppuccin Frappe",
    "Catppuccin Frappé (Gogh)",
    "Catppuccin Macchiato",
    "Catppuccin Macchiato (Gogh)",
    "Catppuccin Mocha",
    "Catppuccin Mocha (Gogh)",
    "catppuccin-frappe",
    "catppuccin-macchiato",
    "catppuccin-mocha",
    "CGA",
    "Chalk",
    "Chalk (base16)",
    "Chalk (dark) (terminal.sexy)",
    "Chalk (Gogh)",
    "Chalkboard",
    "Chalkboard (Gogh)",
    "ChallengerDeep",
    "Chameleon (Gogh)",
    "Chester",
    "Ciapre",
    "Ciapre (Gogh)",
    "Circus (base16)",
    "City Lights (Gogh)",
    "City Streets (terminal.sexy)",
    "Classic Dark (base16)",
    "Clone Of Ubuntu (Gogh)",
    "Cloud (terminal.sexy)",
    "Cobalt 2 (Gogh)",
    "Cobalt Neon",
    "Cobalt Neon (Gogh)",
    "Cobalt2",
    "Codeschool (base16)",
    "Codeschool (dark) (terminal.sexy)",
    "Color Star (terminal.sexy)",
    "Colorful Colors (terminal.sexy)",
    "Colors (base16)",
    "Count Von Count (terminal.sexy)",
    "Crayon Pony Fish (Gogh)",
    "CrayonPonyFish",
    "CutiePro",
    "Cyberdyne",
    "cyberpunk",
    "DanQing (base16)",
    "Darcula (base16)",
    "Dark Ocean (terminal.sexy)",
    "Dark Pastel",
    "Dark Pastel (Gogh)",
    "Dark Violet (base16)",
    "Dark+",
    "darkermatrix",
    "darkmatrix",
    "darkmoss (base16)",
    "Darkside",
    "Darkside (Gogh)",
    "Darktooth (base16)",
    "Dawn (terminal.sexy)",
    "Deafened (terminal.sexy)",
    "Decaf (base16)",
    "deep",
    "Default (dark) (terminal.sexy)",
    "Default Dark (base16)",
    "Dehydration (Gogh)",
    "Derp (terminal.sexy)",
    "Desert",
    "Desert (Gogh)",
    "Digerati (terminal.sexy)",
    "Dimmed Monokai (Gogh)",
    "DimmedMonokai",
    "Dissonance (Gogh)",
    "Django",
    "DjangoRebornAgain",
    "DjangoSmooth",
    "Doom Peacock",
    "DoomOne",
    "DotGov",
    "Dotshare (terminal.sexy)",
    "Dracula",
    "Dracula (base16)",
    "Dracula (Gogh)",
    "Dracula (Official)",
    "Dracula+",
    "duckbones",
    "Duotone Dark",
    "duskfox",
    "DWM rob (terminal.sexy)",
    "Earthsong",
    "Earthsong (Gogh)",
    "Edge Dark (base16)",
    "Ef-Autumn",
    "Ef-Bio",
    "Ef-Cherie",
    "Ef-Dark",
    "Ef-Deuteranopia-Dark",
    "Ef-Dream",
    "Ef-Duo-Dark",
    "Ef-Elea-Dark",
    "Ef-Maris-Dark",
    "Ef-Melissa-Dark",
    "Ef-Night",
    "Ef-Rosa",
    "Ef-Symbiosis",
    "Ef-Trio-Dark",
    "Ef-Tritanopia-Dark",
    "Ef-Winter",
    "Eighties (base16)",
    "Eighties (dark) (terminal.sexy)",
    "Eldorado dark (terminal.sexy)",
    "Eldritch",
    "Elemental",
    "Elemental (Gogh)",
    "Elementary",
    "Elementary (Gogh)",
    "Elic (Gogh)",
    "Elio (Gogh)",
    "Embers (base16)",
    "Embers (dark) (terminal.sexy)",
    "ENCOM",
    "Epiphany (terminal.sexy)",
    "Eqie6 (terminal.sexy)",
    "Equilibrium Dark (base16)",
    "Equilibrium Gray Dark (base16)",
    "Erebus (terminal.sexy)",
    "Espresso",
    "Espresso (base16)",
    "Espresso (Gogh)",
    "Espresso Libre",
    "Espresso Libre (Gogh)",
    "Eva (base16)",
    "Eva Dim (base16)",
    "Everblush",
    "Everblush (Gogh)",
    "Everforest Dark (Gogh)",
    "Everforest Dark Hard (Gogh)",
    "Everforest Dark Medium (Gogh)",
    "Everforest Dark Soft (Gogh)",
    "Fahrenheit",
    "Fairy Floss (Gogh)",
    "Fairy Floss Dark (Gogh)",
    "Fairyfloss",
    "farmhouse-dark",
    "FarSide (terminal.sexy)",
    "Fideloper",
    "Firefly Traditional",
    "FirefoxDev",
    "Firewatch",
    "Fishbone (terminal.sexy)",
    "FishTank",
    "Fishtank (Gogh)",
    "Flat",
    "Flat (base16)",
    "Flat (Gogh)",
    "Flat Remix (Gogh)",
    "Flatland",
    "Flatland (Gogh)",
    "flexoki-dark",
    "Floraverse",
    "ForestBlue",
    "Foxnightly (Gogh)",
    "Framer",
    "Framer (base16)",
    "Freya (Gogh)",
    "Frontend Delight (Gogh)",
    "Frontend Fun Forrest (Gogh)",
    "Frontend Galaxy (Gogh)",
    "FrontEndDelight",
    "FunForrest",
    "Galaxy",
    "Galizur",
    "Geohot (Gogh)",
    "Gigavolt (base16)",
    "GitHub Dark",
    "Github Dark (Gogh)",
    "GJM (terminal.sexy)",
    "Glacier",
    "Gnometerm (terminal.sexy)",
    "Gogh (Gogh)",
    "Gooey (Gogh)",
    "Google (dark) (terminal.sexy)",
    "Google Dark (base16)",
    "Google Dark (Gogh)",
    "Gotham (Gogh)",
    "Gotham (terminal.sexy)",
    "Grandshell (terminal.sexy)",
    "Grape",
    "Grape (Gogh)",
    "Grass",
    "Grass (Gogh)",
    "Grayscale (dark) (terminal.sexy)",
    "Grayscale Dark (base16)",
    "Green Screen (base16)",
    "Greenscreen (dark) (terminal.sexy)",
    "Grey-green",
    "Gruber (base16)",
    "Gruvbox Dark (Gogh)",
    "Gruvbox dark, hard (base16)",
    "Gruvbox dark, medium (base16)",
    "Gruvbox dark, pale (base16)",
    "Gruvbox dark, soft (base16)",
    "Gruvbox Material (Gogh)",
    "GruvboxDark",
    "GruvboxDarkHard",
    "Guezwhoz",
    "Hacktober",
    "Hardcore",
    "Hardcore (base16)",
    "Hardcore (Gogh)",
    "hardhacker",
    "Harmonic16 Dark (base16)",
    "Harper",
    "Harper (Gogh)",
    "HaX0R_BLUE",
    "HaX0R_GR33N",
    "HaX0R_R3D",
    "Heetch Dark (base16)",
    "Helios (base16)",
    "Hemisu Dark (Gogh)",
    "Highway",
    "Highway (Gogh)",
    "Hipster Green",
    "Hipster Green (Gogh)",
    "Hivacruz",
    "Homebrew",
    "Homebrew (Gogh)",
    "Homebrew Ocean (Gogh)",
    "Hopscotch",
    "Hopscotch (base16)",
    "Hopscotch.256",
    "Horizon Dark (base16)",
    "Horizon Dark (Gogh)",
    "Humanoid dark (base16)",
    "hund (terminal.sexy)",
    "Hurtado",
    "Hurtado (Gogh)",
    "Hybrid",
    "Hybrid (Gogh)",
    "Hybrid (terminal.sexy)",
    "Ibm 3270 (High Contrast) (Gogh)",
    "Ibm3270 (Gogh)",
    "Ic Green Ppl (Gogh)",
    "Ic Orange Ppl (Gogh)",
    "IC_Green_PPL",
    "IC_Orange_PPL",
    "Iceberg (Gogh)",
    "iceberg-dark",
    "Icy Dark (base16)",
    "idea",
    "Idle Toes (Gogh)",
    "idleToes",
    "Iiamblack (terminal.sexy)",
    "Insignificato (terminal.sexy)",
    "Invisibone (terminal.sexy)",
    "IR Black (base16)",
    "Ir Black (Gogh)",
    "IR_Black",
    "Isotope (base16)",
    "Isotope (dark) (terminal.sexy)",
    "iTerm2 Dark Background",
    "iTerm2 Default",
    "iTerm2 Pastel Dark Background",
    "iTerm2 Smoooooth",
    "iTerm2 Tango Dark",
    "Ivory Dark (terminal.sexy)",
    "Jackie Brown",
    "Jackie Brown (Gogh)",
    "Japanesque",
    "Japanesque (Gogh)",
    "Jason Wryan (terminal.sexy)",
    "Jellybeans",
    "Jellybeans (Gogh)",
    "JetBrains Darcula",
    "jmbi (terminal.sexy)",
    "jubi",
    "JWR dark (terminal.sexy)",
    "Kanagawa (Gogh)",
    "Kanagawa Dragon (Gogh)",
    "kanagawabones",
    "Kasugano (terminal.sexy)",
    "Kibble",
    "Kibble (Gogh)",
    "Kimber (base16)",
    "Kokuban (Gogh)",
    "Kolorit",
    "Konsolas",
    "kurokula",
    "Lab Fox",
    "Laser",
    "Laserwave (Gogh)",
    "Later This Evening",
    "Later This Evening (Gogh)",
    "Lavandula",
    "Lavandula (Gogh)",
    "Light White (terminal.sexy)",
    "Liquid Carbon (Gogh)",
    "Liquid Carbon Transparent (Gogh)",
    "LiquidCarbon",
    "LiquidCarbonTransparent",
    "LiquidCarbonTransparentInverse",
    "London Tube (base16)",
    "Londontube (dark) (terminal.sexy)",
    "Lost Woods (terminal.sexy)",
    "lovelace",
    "Low Contrast (terminal.sexy)",
    "Lumifoo (terminal.sexy)",
    "Lunaria Dark (Gogh)",
    "Lunaria Eclipse (Gogh)",
    "Macintosh (base16)",
    "Maia (Gogh)",
    "Mariana",
    "Marrakesh (base16)",
    "Marrakesh (dark) (terminal.sexy)",
    "Mashup Colors (terminal.sexy)",
    "Materia (base16)",
    "Material (base16)",
    "Material (Gogh)",
    "Material (terminal.sexy)",
    "Material Darker (base16)",
    "Material Palenight (base16)",
    "Material Vivid (base16)",
    "MaterialDark",
    "MaterialDarker",
    "MaterialDesignColors",
    "MaterialOcean",
    "Mathias",
    "Mathias (Gogh)",
    "matrix",
    "Matrix (terminal.sexy)",
    "Medallion",
    "Medallion (Gogh)",
    "Mellifluous",
    "Mellow Purple (base16)",
    "midnight-in-mojave",
    "Mikado (terminal.sexy)",
    "Mikazuki (terminal.sexy)",
    "Mirage",
    "Miramare (Gogh)",
    "Misterioso",
    "Misterioso (Gogh)",
    "Mocha (base16)",
    "Mocha (dark) (terminal.sexy)",
    "Modus Vivendi (Gogh)",
    "Modus Vivendi Tinted (Gogh)",
    "Modus-Vivendi",
    "Modus-Vivendi-Deuteranopia",
    "Modus-Vivendi-Tinted",
    "Modus-Vivendi-Tritanopia",
    "Molokai",
    "Molokai (Gogh)",
    "Mona Lisa (Gogh)",
    "MonaLisa",
    "Mono (terminal.sexy)",
    "Mono Amber (Gogh)",
    "Mono Cyan (Gogh)",
    "Mono Green (Gogh)",
    "Mono Red (Gogh)",
    "Mono Theme (terminal.sexy)",
    "Mono White (Gogh)",
    "Mono Yellow (Gogh)",
    "Monokai (base16)",
    "Monokai (dark) (terminal.sexy)",
    "Monokai (terminal.sexy)",
    "Monokai Dark (Gogh)",
    "Monokai Pro (Gogh)",
    "Monokai Pro Ristretto (Gogh)",
    "Monokai Remastered",
    "Monokai Soda",
    "Monokai Soda (Gogh)",
    "Monokai Vivid",
    "Moonfly (Gogh)",
    "Morada (Gogh)",
    "Muse (terminal.sexy)",
    "N0tch2k",
    "N0Tch2K (Gogh)",
    "Nancy (terminal.sexy)",
    "Nature Suede (terminal.sexy)",
    "Navy and Ivory (terminal.sexy)",
    "Nebula (base16)",
    "neobones_dark",
    "Neon",
    "Neon (terminal.sexy)",
    "Neon Night (Gogh)",
    "Neopolitan",
    "Neopolitan (Gogh)",
    "Neutron",
    "Neutron (Gogh)",
    "Night Owl (Gogh)",
    "Nightfly (Gogh)",
    "nightfox",
    "NightLion v1",
    "Nightlion V1 (Gogh)",
    "NightLion v2",
    "Nightlion V2 (Gogh)",
    "Nighty (Gogh)",
    "niji",
    "Nocturnal Winter",
    "nord",
    "Nord (base16)",
    "Nord (Gogh)",
    "nordfox",
    "Nova (base16)",
    "Nucolors (terminal.sexy)",
    "Nudge (terminal.sexy)",
    "Numix Darkest (terminal.sexy)",
    "NvimDark",
    "Obsidian",
    "Obsidian (Gogh)",
    "Ocean",
    "Ocean (base16)",
    "Ocean (dark) (terminal.sexy)",
    "Ocean Dark (Gogh)",
    "Oceanic Next (Gogh)",
    "Oceanic-Next",
    "OceanicMaterial",
    "OceanicNext (base16)",
    "Ollie",
    "Ollie (Gogh)",
    "Omni (Gogh)",
    "One Dark (Gogh)",
    "One Half Black (Gogh)",
    "OneDark (base16)",
    "OneHalfDark",
    "Operator Mono Dark",
    "Orangish (terminal.sexy)",
    "Outrun Dark (base16)",
    "Overnight Slumber",
    "Oxocarbon Dark (Gogh)",
    "Palenight (Gogh)",
    "PaleNightHC",
    "Pali (Gogh)",
    "Panda (Gogh)",
    "Pandora",
    "Panels (terminal.sexy)",
    "PaperColor Dark (base16)",
    "Papercolor Dark (Gogh)",
    "Paraiso (base16)",
    "Paraiso (dark) (terminal.sexy)",
    "Paraiso Dark",
    "Paraiso Dark (Gogh)",
    "Parker Brothers (terminal.sexy)",
    "Pasque (base16)",
    "Pastel White (terminal.sexy)",
    "Paul Millr (Gogh)",
    "PaulMillr",
    "Pencil Dark (Gogh)",
    "PencilDark",
    "Peppermint",
    "Peppermint (Gogh)",
    "PhD (base16)",
    "Phrak1 (terminal.sexy)",
    "Pico (base16)",
    "pinky (base16)",
    "Pixiefloss (Gogh)",
    "Pnevma",
    "Pnevma (Gogh)",
    "Poimandres",
    "Poimandres Storm",
    "Pop (base16)",
    "Popping and Locking",
    "Porple (base16)",
    "Powershell (Gogh)",
    "Predawn (Gogh)",
    "Pretty and Pastel (terminal.sexy)",
    "Pro",
    "Pro (Gogh)",
    "Pulp (terminal.sexy)",
    "Purple People Eater (Gogh)",
    "Purple Rain",
    "Purpledream (base16)",
    "purplepeter",
    "Qualia (base16)",
    "Quiet (Gogh)",
    "Railscasts (base16)",
    "Railscasts (dark) (terminal.sexy)",
    "Rapture",
    "Rasi (terminal.sexy)",
    "Raycast_Dark",
    "rebecca",
    "Rebecca (base16)",
    "Red Alert",
    "Red Alert (Gogh)",
    "Red Phoenix (terminal.sexy)",
    "Red Planet",
    "Red Sands",
    "Red Sands (Gogh)",
    "Relaxed",
    "Relaxed (Gogh)",
    "Retro",
    "Rezza (terminal.sexy)",
    "Rippedcasts",
    "Rippedcasts (Gogh)",
    "rose-pine",
    "rose-pine-moon",
    "Rosé Pine (base16)",
    "Rosé Pine (Gogh)",
    "Rosé Pine Moon (base16)",
    "Rosé Pine Moon (Gogh)",
    "Rouge 2",
    "Royal",
    "Royal (Gogh)",
    "Rydgel (terminal.sexy)",
    "Ryuuko",
    "s3r0 modified (terminal.sexy)",
    "Sakura",
    "Sandcastle (base16)",
    "Scarlet Protocol",
    "Sea Shells (Gogh)",
    "Seafoam Pastel",
    "Seafoam Pastel (Gogh)",
    "SeaShells",
    "Selenized Black (Gogh)",
    "Selenized Dark (Gogh)",
    "Seoul256 (Gogh)",
    "seoulbones_dark",
    "Sequoia Monochrome",
    "Sequoia Moonlight",
    "Seti",
    "Seti (Gogh)",
    "Seti UI (base16)",
    "Sex Colors (terminal.sexy)",
    "Shades of Purple (base16)",
    "shades-of-purple",
    "Shaman",
    "Shaman (Gogh)",
    "Shapeshifter (dark) (terminal.sexy)",
    "Shel (Gogh)",
    "Shic (terminal.sexy)",
    "Silk Dark (base16)",
    "Simple Rainbow (terminal.sexy)",
    "Slate",
    "Slate (Gogh)",
    "SleepyHollow",
    "Smyck",
    "Smyck (Gogh)",
    "Snazzy",
    "Snazzy (base16)",
    "Snazzy (Gogh)",
    "Soft Server (Gogh)",
    "SoftServer",
    "Solar Flare (base16)",
    "Solarized (dark) (terminal.sexy)",
    "Solarized Darcula",
    "Solarized Darcula (Gogh)",
    "Solarized Dark (Gogh)",
    "Solarized Dark - Patched",
    "Solarized Dark Higher Contrast",
    "Solarized Dark Higher Contrast (Gogh)",
    "Sonokai (Gogh)",
    "SOS (terminal.sexy)",
    "Spacedust",
    "Spacedust (Gogh)",
    "SpaceGray",
    "Spacegray (Gogh)",
    "SpaceGray Eighties",
    "Spacegray Eighties (Gogh)",
    "SpaceGray Eighties Dull",
    "Spacegray Eighties Dull (Gogh)",
    "Spacemacs (base16)",
    "Sparky (Gogh)",
    "Spiderman",
    "Splurge (terminal.sexy)",
    "Spring (Gogh)",
    "Square",
    "Square (Gogh)",
    "Srcery (Gogh)",
    "Sublette",
    "Subliminal",
    "Sugarplum",
    "Summer Pop (Gogh)",
    "summercamp (base16)",
    "Summerfruit Dark (base16)",
    "Sundried",
    "Sundried (Gogh)",
    "Swayr (terminal.sexy)",
    "Sweet Eliverlara (Gogh)",
    "Sweet Love (terminal.sexy)",
    "Sweet Terminal (Gogh)",
    "Symfonic",
    "Symphonic (Gogh)",
    "Synth Midnight Terminal Dark (base16)",
    "synthwave",
    "Synthwave (Gogh)",
    "Synthwave Alpha (Gogh)",
    "synthwave-everything",
    "SynthwaveAlpha",
    "Tango (base16)",
    "Tango (terminal.sexy)",
    "Tangoesque (terminal.sexy)",
    "Tartan (terminal.sexy)",
    "Teerb",
    "Teerb (Gogh)",
    "tender (base16)",
    "Tender (Gogh)",
    "terafox",
    "Terminix Dark (Gogh)",
    "Teva (terminal.sexy)",
    "Thayer Bright",
    "Thayer Bright (Gogh)",
    "The Hulk",
    "theme2 (terminal.sexy)",
    "thwump (terminal.sexy)",
    "Tin (Gogh)",
    "Tinacious Design (Dark)",
    "tlh (terminal.sexy)",
    "Tokyo Night",
    "Tokyo Night (Gogh)",
    "Tokyo Night Moon",
    "Tokyo Night Storm",
    "Tokyo Night Storm (Gogh)",
    "tokyonight",
    "tokyonight-storm",
    "tokyonight_moon",
    "tokyonight_night",
    "tokyonight_storm",
    "Tomorrow (dark) (terminal.sexy)",
    "Tomorrow Night",
    "Tomorrow Night (Gogh)",
    "Tomorrow Night Blue",
    "Tomorrow Night Blue (Gogh)",
    "Tomorrow Night Bright",
    "Tomorrow Night Bright (Gogh)",
    "Tomorrow Night Burns",
    "Tomorrow Night Eighties",
    "Tomorrow Night Eighties (Gogh)",
    "Toy Chest (Gogh)",
    "ToyChest",
    "Treehouse",
    "Treehouse (Gogh)",
    "Trim Yer Beard (terminal.sexy)",
    "Twilight",
    "Twilight (base16)",
    "Twilight (dark) (terminal.sexy)",
    "Twilight (Gogh)",
    "Ubuntu",
    "UltraDark",
    "UltraViolent",
    "UnderTheSea",
    "Unikitty Dark (base16)",
    "Unikitty Reversible (base16)",
    "Unsifted Wheat (terminal.sexy)",
    "Urple",
    "Urple (Gogh)",
    "Vacuous 2 (terminal.sexy)",
    "Vag (Gogh)",
    "Vaughn",
    "Vaughn (Gogh)",
    "Vesper",
    "Vibrant Ink (Gogh)",
    "VibrantInk",
    "Vice Alt (base16)",
    "Vice Dark (base16)",
    "Violet Dark",
    "VisiBlue (terminal.sexy)",
    "VisiBone (terminal.sexy)",
    "Visibone Alt. 2 (terminal.sexy)",
    "Vs Code Dark+ (Gogh)",
    "vulcan (base16)",
    "VWbug (terminal.sexy)",
    "Warm Neon (Gogh)",
    "WarmNeon",
    "Website (Gogh)",
    "Wez",
    "Wez (Gogh)",
    "Whimsy",
    "Wild Cherry (Gogh)",
    "WildCherry",
    "wilmersdorf",
    "Windows 10 (base16)",
    "Windows 95 (base16)",
    "Windows High Contrast (base16)",
    "Windows NT (base16)",
    "Wombat",
    "Wombat (Gogh)",
    "Woodland (base16)",
    "Wryan",
    "Wryan (Gogh)",
    "Wzoreck (Gogh)",
    "X::DotShare (terminal.sexy)",
    "X::Erosion (terminal.sexy)",
    "XCode Dusk (base16)",
    "zenbones_dark",
    "Zenburn",
    "Zenburn (base16)",
    "Zenburn (Gogh)",
    "zenburn (terminal.sexy)",
    "zenburned",
    "zenwritten_dark",
  },
  light = {
    "3024 (light) (terminal.sexy)",
    "3024 Day",
    "3024 Day (Gogh)",
    "aikofog (terminal.sexy)",
    "Alabaster",
    "Ashes (light) (terminal.sexy)",
    "Atelier Cave Light (base16)",
    "Atelier Dune Light (base16)",
    "Atelier Estuary Light (base16)",
    "Atelier Forest Light (base16)",
    "Atelier Heath Light (base16)",
    "Atelier Lakeside Light (base16)",
    "Atelier Plateau Light (base16)",
    "Atelier Savanna Light (base16)",
    "Atelier Seaside Light (base16)",
    "Atelier Sulphurpool Light (base16)",
    "Atelierdune (light) (terminal.sexy)",
    "Atelierforest (light) (terminal.sexy)",
    "Atelierheath (light) (terminal.sexy)",
    "Atelierlakeside (light) (terminal.sexy)",
    "Atelierseaside (light) (terminal.sexy)",
    "AtomOneLight",
    "Ayu Light (Gogh)",
    "ayu_light",
    "Bamboo Light",
    "Belafonte Day",
    "Belafonte Day (Gogh)",
    "Bespin (light) (terminal.sexy)",
    "Bluloco Light (Gogh)",
    "Bluloco Zsh Light (Gogh)",
    "BlulocoLight",
    "Breadog (Gogh)",
    "Breath Light (Gogh)",
    "Brewer (light) (terminal.sexy)",
    "Brush Trees (base16)",
    "Builtin Light",
    "Builtin Solarized Light",
    "Builtin Tango Light",
    "Catppuccin Latte",
    "Catppuccin Latte (Gogh)",
    "catppuccin-latte",
    "Chalk (light) (terminal.sexy)",
    "Classic Light (base16)",
    "CLRS",
    "Clrs (Gogh)",
    "Codeschool (light) (terminal.sexy)",
    "coffee_theme",
    "Colorcli (Gogh)",
    "Cupcake (base16)",
    "Cupertino (base16)",
    "DanQing Light (base16)",
    "dawnfox",
    "dayfox",
    "Default (light) (terminal.sexy)",
    "Default Light (base16)",
    "dirtysea (base16)",
    "Edge Light (base16)",
    "Ef-Arbutus",
    "Ef-Cyprus",
    "Ef-Day",
    "Ef-Deuteranopia-Light",
    "Ef-Duo-Light",
    "Ef-Elea-Light",
    "Ef-Frost",
    "Ef-Kassio",
    "Ef-Light",
    "Ef-Maris-Light",
    "Ef-Melissa-Light",
    "Ef-Reverie",
    "Ef-Spring",
    "Ef-Summer",
    "Ef-Trio-Light",
    "Ef-Tritanopia-Light",
    "Eighties (light) (terminal.sexy)",
    "Embers (light) (terminal.sexy)",
    "Equilibrium Gray Light (base16)",
    "Equilibrium Light (base16)",
    "Euphrasia (terminal.sexy)",
    "Everforest Light (Gogh)",
    "Everforest Light Hard (Gogh)",
    "Everforest Light Medium (Gogh)",
    "Everforest Light Soft (Gogh)",
    "farmhouse-light",
    "flexoki-light",
    "Fruit Soda (base16)",
    "Github",
    "Github (base16)",
    "Github (Gogh)",
    "Github Light (Gogh)",
    "Google (light) (terminal.sexy)",
    "Google Light (base16)",
    "Google Light (Gogh)",
    "Grayscale (light) (terminal.sexy)",
    "Grayscale Light (base16)",
    "Greenscreen (light) (terminal.sexy)",
    "Gruvbox (Gogh)",
    "Gruvbox light, hard (base16)",
    "Gruvbox light, medium (base16)",
    "Gruvbox light, soft (base16)",
    "GruvboxLight",
    "Harmonic16 Light (base16)",
    "Heetch Light (base16)",
    "Hemisu Light (Gogh)",
    "Homebrew Light (Gogh)",
    "Horizon Bright (Gogh)",
    "Horizon Light (base16)",
    "Humanoid light (base16)",
    "iceberg-light",
    "Isotope (light) (terminal.sexy)",
    "iTerm2 Light Background",
    "iTerm2 Tango Light",
    "Ivory Light (terminal.sexy)",
    "Jup (Gogh)",
    "Londontube (light) (terminal.sexy)",
    "Lunaria Light (Gogh)",
    "Man Page",
    "Man Page (Gogh)",
    "Mar (Gogh)",
    "Marrakesh (light) (terminal.sexy)",
    "Material",
    "Material Lighter (base16)",
    "Mexico Light (base16)",
    "Mocha (light) (terminal.sexy)",
    "Modus Operandi (Gogh)",
    "Modus Operandi Tinted (Gogh)",
    "Modus-Operandi",
    "Modus-Operandi-Deuteranopia",
    "Modus-Operandi-Tinted",
    "Monokai (light) (terminal.sexy)",
    "Mostly Bright (terminal.sexy)",
    "neobones_light",
    "Nep (Gogh)",
    "Night Owlish Light",
    "Nord Light (Gogh)",
    "nord-light",
    "Novel",
    "Novel (Gogh)",
    "NvimLight",
    "Ocean (light) (terminal.sexy)",
    "One Light (base16)",
    "One Light (Gogh)",
    "OneHalfLight",
    "Paper (Gogh)",
    "PaperColor Light (base16)",
    "Papercolor Light (Gogh)",
    "Paraiso (light) (terminal.sexy)",
    "Pencil Light (Gogh)",
    "PencilLight",
    "Piatto Light",
    "primary",
    "Pro Light",
    "Railscasts (light) (terminal.sexy)",
    "Raycast_Light",
    "rose-pine-dawn",
    "Rosé Pine Dawn (base16)",
    "Rosé Pine Dawn (Gogh)",
    "Sagelight (base16)",
    "Sakura (base16)",
    "Sat (Gogh)",
    "Selenized Light (Gogh)",
    "Selenized White (Gogh)",
    "Seoul256 Light (Gogh)",
    "seoulbones_light",
    "Shapeshifter (base16)",
    "Shapeshifter (light) (terminal.sexy)",
    "Silk Light (base16)",
    "Solar Flare Light (base16)",
    "Solarized (light) (terminal.sexy)",
    "Solarized Light (Gogh)",
    "Spring",
    "Summerfruit Light (base16)",
    "Synth Midnight Terminal Light (base16)",
    "Tango Adapted",
    "Tango Half Adapted",
    "Terminal Basic",
    "Terminal Basic (Gogh)",
    "Tinacious Design (Light)",
    "Tokyo Night Day",
    "Tokyo Night Light (Gogh)",
    "tokyonight-day",
    "tokyonight_day",
    "Tomorrow",
    "Tomorrow (Gogh)",
    "Tomorrow (light) (terminal.sexy)",
    "Twilight (light) (terminal.sexy)",
    "Unikitty",
    "Unikitty Light (base16)",
    "Ura (Gogh)",
    "vimbones",
    "Violet Light",
    "Vs Code Light+ (Gogh)",
    "Windows 10 Light (base16)",
    "Windows 95 Light (base16)",
    "Windows High Contrast Light (base16)",
    "Windows NT Light (base16)",
    "Yousai (terminal.sexy)",
    "zenbones",
    "zenwritten_light",
  },
}
