#!/usr/bin/env python3
"""Regenerate color_schemes.lua from the FrankenTerm fork's built-in schemes.

The Lua API has no way to list the built-in color schemes or read their
colors, so wezterm.lua loads this generated file instead. It holds the scheme
names, split into dark and light, and the colors the tab bar is built from.

Usage: gen-color-schemes.py [path to scheme_data.rs]
Without a path it reads frankenterm/config/src/scheme_data.rs from the
oystein/main branch of ~/src/frankenterm.
"""

import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

OUT = Path(__file__).resolve().parent / "color_schemes.lua"
REPO = Path.home() / "src/frankenterm"
SCHEME_DATA = "frankenterm/config/src/scheme_data.rs"


def read_source() -> str:
    if len(sys.argv) > 1:
        return Path(sys.argv[1]).read_text()
    return subprocess.run(
        ["git", "-C", str(REPO), "show", f"fork/oystein/main:{SCHEME_DATA}"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def rust_str(literal: str) -> str:
    """Decode a Rust string literal. JSON reads it once \\u{...} escapes are rewritten."""

    def unicode(m: re.Match) -> str:
        return "\\u%04x" % int(m.group(1), 16)

    return json.loads(re.sub(r"\\u\{([0-9a-fA-F]+)\}", unicode, literal))


def luminance(hex_color: str) -> float:
    def linear(c: float) -> float:
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (int(hex_color[i : i + 2], 16) / 255 for i in (1, 3, 5))
    return 0.2126 * linear(r) + 0.7152 * linear(g) + 0.0722 * linear(b)


def lua_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    pairs = re.findall(
        r'\(\n        ("(?:[^"\\]|\\.)*"),\n        ("(?:[^"\\]|\\.)*"),\n    \)',
        read_source(),
    )
    dark, light, colors = [], [], []
    for name_literal, toml_literal in pairs:
        name = rust_str(name_literal)
        scheme = tomllib.loads(rust_str(toml_literal))["colors"]
        bg, fg = scheme.get("background"), scheme.get("foreground")
        if not (bg and fg):
            continue
        (dark if luminance(bg) < 0.18 else light).append(name)
        ansi = scheme.get("ansi") or []
        fields = [f"bg = {lua_str(bg)}", f"fg = {lua_str(fg)}"]
        if len(ansi) == 8:
            fields += [f"yellow = {lua_str(ansi[3])}", f"cyan = {lua_str(ansi[6])}"]
        if "tab_bar" in scheme:
            fields.append("tab_bar = true")
        colors.append(f"    [{lua_str(name)}] = {{ {', '.join(fields)} }},")

    lines = [
        "-- Built-in color scheme names, dark ones first, and the colors the tab bar",
        "-- is built from. Generated by gen-color-schemes.py from the fork's",
        f"-- {SCHEME_DATA} (the Lua API cannot list schemes or read their colors).",
        "-- tab_bar = true marks a scheme that sets its own tab bar colors.",
        "return {",
        "  dark = {",
        *(f"    {lua_str(n)}," for n in dark),
        "  },",
        "  light = {",
        *(f"    {lua_str(n)}," for n in light),
        "  },",
        "  colors = {",
        *colors,
        "  },",
        "}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT}: {len(dark)} dark, {len(light)} light")


if __name__ == "__main__":
    main()
