#!/usr/bin/env bash
# Optional. The gate does NOT need this.
#
# The scorer imports nothing outside the standard library, so the hook runs it
# with bare `python3` and a PYTHONPATH. A repository that carries this skill and
# wires the hook in its own .claude/settings.json needs no install step at all.
#
# What this script is for: putting a `pl` command on your PATH, so you can score
# a file by hand without remembering the invocation. Nothing else depends on it.
#
#   ./install.sh              # install `pl`
#   ./install.sh --check      # just run the self test
set -euo pipefail

SKILL_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${PLAINLANG_BIN_DIR:-$HOME/bin}"

if [ "${1:-}" = "--check" ]; then
  exec bash "$SKILL_DIR/selftest.sh"
fi

if ! python3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 12) else 1)' 2>/dev/null; then
  echo "python3 is $(python3 -V 2>&1), and this needs 3.12 or newer." >&2
  echo "The gate will report itself as broken at session start until that is fixed." >&2
  exit 1
fi

mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/pl" <<LAUNCHER
#!/bin/sh
# Plain-language scorer. Generated by $SKILL_DIR/install.sh.
SKILL="\${PLAINLANG_HOME:-$SKILL_DIR}"
PLAINLANG_LEXICON="\${PLAINLANG_LEXICON:-\$SKILL/data/lexicon.tsv.gz}" \\
PYTHONPATH="\$SKILL/tool/src\${PYTHONPATH:+:\$PYTHONPATH}" \\
  exec python3 -m plainlang.cli "\$@"
LAUNCHER
chmod +x "$BIN_DIR/pl"
echo "installed $BIN_DIR/pl"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "note: $BIN_DIR is not on your PATH" ;;
esac

echo
exec bash "$SKILL_DIR/selftest.sh"
