#!/usr/bin/env bash
# scaffold-onboarding.sh — create the .claude/support-triage/ skeleton
#
# Usage:  scaffold-onboarding.sh /path/to/project

set -euo pipefail

PROJECT="${1:-}"
[[ -d "$PROJECT" ]] || { echo "usage: scaffold-onboarding.sh <project-path>" >&2; exit 2; }
PROJECT="$(cd "$PROJECT" && pwd)"

OUT="$PROJECT/.claude/support-triage"
mkdir -p \
  "$OUT/04-templates" \
  "$OUT/11-runbooks" \
  "$OUT/vocabularies" \
  "$OUT/artifacts/evidence" \
  "$OUT/artifacts/drafts" \
  "$OUT/artifacts/approvals" \
  "$OUT/artifacts/sends" \
  "$OUT/artifacts/verification" \
  "$OUT/artifacts/manifests" \
  "$OUT/handoffs" \
  "$OUT/outcomes" \
  "$OUT/.workspace" \
  "$OUT/scripts"

# Don't clobber existing artifacts
write_if_absent() {
  local path="$1" content="$2"
  if [[ -e "$path" ]]; then
    echo "→ exists, skipping: $path"
  else
    printf '%s' "$content" > "$path"
    echo "→ wrote: $path"
  fi
}

write_executable_if_absent() {
  local path="$1" content="$2"
  if [[ -e "$path" ]]; then
    echo "→ exists, skipping: $path"
  else
    printf '%s' "$content" > "$path"
    chmod +x "$path"
    echo "→ wrote: $path"
  fi
}

json_escape() {
  local value="$1"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//$'\n'/\\n}
  value=${value//$'\r'/\\r}
  value=${value//$'\t'/\\t}
  printf '%s' "$value"
}

write_if_absent "$OUT/README.md" "# Support Triage — $(basename "$PROJECT")

This folder is the agent-readable map of how user support works for this project.
Generated by the user-support-triage skill on $(date -u +%F).
See the skill's assets/ONBOARDING-TEMPLATE.md for the canonical structure.
"

write_if_absent "$OUT/00-intake.md" "# Support Intake — TODO

Lifecycle mode: onboarding.
Complexity band: unknown.

## Source Anchors

| Rule/fact | Source |
|---|---|
| Initial scaffold created | fire-drill:scaffold-onboarding |

## Routers Used

| Router | Branches |
|---|---|
| Surface | TBD |
| Risk | TBD |
| Audience | TBD |
| Provider | TBD |
| Support archetype | TBD |

Record owner decisions and source anchors. See SUPPORT-INTAKE-ROUTER.md for the
full flow.
"

write_if_absent "$OUT/01-architecture.md" "# Support Architecture — TODO

Run codebase-archaeology + codebase-report on this project,
focusing on support code paths, then fill this in following the template at
ONBOARDING-TEMPLATE.md > '01-architecture.md'.
"

write_if_absent "$OUT/02-channels.md" "# Support Channels — TODO

List every place users can reach the project. Don't miss email bounces,
community/social channels, marketplace/app-store reviews, customer-success
threads, sales handoffs, internal ops queues, or partner channels.

Manual-only channels must name an owner and review cadence. If there are none,
write \"manual-only channels: none known\" with a source anchor.

See ONBOARDING-TEMPLATE.md > '02-channels.md'.
"

write_if_absent "$OUT/03-decision-matrix.md" "# Decision Matrix — TODO

Project-specific override of the generic matrix in the skill's references/.
"

write_if_absent "$OUT/04-templates/REQUEST-INFO.md" "# REQUEST-INFO

Draft the project-specific request-for-details reply here after voice calibration.
"

write_if_absent "$OUT/04-templates/BUG-CONFIRMED.md" "# BUG-CONFIRMED

Draft the project-specific confirmed-bug reply here after voice calibration.
"

write_if_absent "$OUT/04-templates/REFUND.md" "# REFUND

Draft refund reply variants here after owner signs off on 05-policies.md.
"

write_if_absent "$OUT/05-policies.md" "# Support Policies — TODO

Run the POLICY-ELICITATION batched prompt, paste owner answers here.
"

write_if_absent "$OUT/06-recurring-issues.md" "# Recurring Issues — TODO

Top categories last 90 days + known silent failures.
"

write_if_absent "$OUT/07-secrets.md" "# Secrets — TODO

Env var NAMES (not values) used by the support pipeline.
"

write_if_absent "$OUT/08-voice.md" "# Voice — TODO

Run the voice-analyst pass on at least 5 historical replies. Record opener,
closer, banned phrases, length targets, and risk-tier mode shifts.
"

write_if_absent "$OUT/09-knowledge-base.md" "# Knowledge Base — TODO

Canonical answers, public docs to link, gaps to fill, and zero-result searches.
"

write_if_absent "$OUT/10-metrics.md" "# Support Metrics — TODO

Baseline FRT, MTTR, SLA breach rate, CSAT/NPS, open volume, and dashboards.
"

write_if_absent "$OUT/adapter-capabilities.json" '{
  "adapter_version": "support-adapter-v1",
  "provider": "project-adapter",
  "read": {
    "list_open": false,
    "fetch_item_detail": false,
    "fetch_sla": false
  },
  "safe_actions": {
    "post_internal_note": false,
    "transition_status": false,
    "file_bead": true
  },
  "unsafe_actions": {
    "send_customer_reply": {
      "supported": false,
      "confirmation_required": true
    },
    "issue_refund": {
      "supported": false,
      "confirmation_required": true
    },
    "public_close_with_comment": {
      "supported": false,
      "confirmation_required": true
    }
  },
  "limits": {
    "pagination": "not implemented yet",
    "rate_limit": "not implemented yet",
    "max_messages_per_item": 0
  }
}
'

write_if_absent "$OUT/11-runbooks/REFUND.md" "# Runbook — REFUND — TODO

Project-specific refund evidence, owner approval path, execution commands, and audit trail.
"

write_if_absent "$OUT/11-runbooks/SECURITY-DISCLOSURE.md" "# Runbook — SECURITY-DISCLOSURE — TODO

Private intake, embargo, severity assessment, owner/security contact, and public disclosure policy.
"

write_if_absent "$OUT/11-runbooks/GDPR-DSAR.md" "# Runbook — GDPR-DSAR — TODO

Identity verification, export/erasure scope, legal hold handling, and completion audit.
"

write_if_absent "$OUT/11-runbooks/HOSTILE-USER.md" "# Runbook — HOSTILE-USER — TODO

Evidence preservation, de-escalation ladder, lock/ban approval path, and owner handoff.
"

write_if_absent "$OUT/11-runbooks/OUTAGE-COMMS.md" "# Runbook — OUTAGE-COMMS — TODO

Status page, broadcast updates, one coordinated customer thread, and post-incident retro link.
"

write_if_absent "$OUT/12-gap-dispositions.md" "# Gap Dispositions — TODO

Every known gap gets one disposition: confirmed, not-applicable, manual-only,
blocked-by-access, provider-gap, policy-gap, evidence-gap, deferred, or unknown.
"

write_if_absent "$OUT/vocabularies/themes.md" "# Theme Vocabulary — TODO

Controlled vocabulary for support theme tags used by 🏷 TAG-CONSISTENCY and
VOICE-OF-CUSTOMER-LOOP.md. Prefer existing tags; propose new tags in outcome
records and promote them only after owner/monthly review.

| Tag | Meaning | Examples | Owner |
|---|---|---|---|
| auth.oauth-flow | OAuth/login callback confusion | redirect mismatch, provider consent loop | support-owner |
| billing.duplicate-charge | Duplicate charge or invoice | same period charged twice | support-owner |
| docs.example-gap | Docs missing a concrete example | user asks for missing API example | support-owner |
| ux.error-message | Error text confused the user | generic error with no next step | support-owner |
"

PROJECT_NAME_JSON="$(json_escape "$(basename "$PROJECT")")"
GENERATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
write_if_absent "$OUT/handoffs/support-handoff.json" "{
  \"schema\": \"support-handoff-v1\",
  \"project\": \"$PROJECT_NAME_JSON\",
  \"generated_at\": \"$GENERATED_AT\",
  \"risk_tier\": \"routine\",
  \"case_ids\": [],
  \"active_channels\": [],
  \"owner_required\": true,
  \"customer_visible_sends_blocked_until_approved\": true,
  \"current_state\": \"onboarding\",
  \"next_owner\": \"support-owner\",
  \"support_archetypes\": [],
  \"support_intelligence\": {
    \"theme_vocabulary\": \".claude/support-triage/vocabularies/themes.md\",
    \"loop_owner\": \"support-owner\",
    \"theme_tags_exported\": false,
    \"persona_tags_exported\": false,
    \"compensation_band_exported\": false,
    \"keeper_consent_exported\": false,
    \"loopback_state_exported\": false
  },
  \"validation\": {
    \"adapter\": \"not-run\",
    \"support_map\": \"not-run\",
    \"fire_drills\": []
  },
  \"artifacts\": {
    \"evidence\": [],
    \"drafts\": [],
    \"approvals\": [],
    \"sends\": [],
    \"verification\": []
  },
  \"gap_dispositions\": []
}
"

# shellcheck disable=SC2016
write_executable_if_absent "$OUT/scripts/list-open.sh" '#!/usr/bin/env bash
set -euo pipefail

SUPPORT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DET="$SUPPORT_DIR/_detection.json"

if [[ ! -f "$DET" ]]; then
  echo "No _detection.json. Run detect-support-surface.sh first." >&2
  exit 2
fi

echo "TODO: replace this placeholder with project-specific list-open logic." >&2
echo "Use _detection.json plus 02-channels.md to pull every supported channel." >&2
NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
sed "s/__NOW__/$NOW/g" <<JSON
[
  {
    "adapter_version": "support-adapter-v1",
    "surface": "project-adapter",
    "provider": "project-adapter",
    "id": "adapter-needed-project",
    "stable_url": null,
    "public_url": null,
    "subject": "Project-specific support adapter needed",
    "category": "adapter",
    "status": "adapter_error",
    "priority": "unknown",
    "created_at": "__NOW__",
    "updated_at": "__NOW__",
    "last_customer_message_at": null,
    "last_support_message_at": null,
    "age_hours": 0,
    "customer": {},
    "sla": {"status": "unknown"},
    "messages": [],
    "labels": ["adapter-needed"],
    "attachments": [],
    "safe_actions": [],
    "unsafe_actions": [],
    "error": {
      "kind": "needs_project_adapter",
      "message": "Replace .claude/support-triage/scripts/list-open.sh with project-specific open-item collection before treating this as a real queue."
    },
    "evidence": [{"kind": "scaffold", "source": "scaffold-onboarding.sh", "checked_at": "__NOW__"}]
  }
]
JSON
'

write_executable_if_absent "$OUT/scripts/post-reply.sh" '#!/usr/bin/env bash
set -euo pipefail

cat >&2 <<EOF
This project-specific sender is intentionally a placeholder.

Before implementing it:
1. Read 05-policies.md and 08-voice.md.
2. Require owner approval for every customer-facing send.
3. Preserve the approved draft in the session workspace.
4. Use provider/internal-note APIs for non-customer-visible notes.
EOF
exit 2
'

echo
echo "→ scaffold ready at: $OUT"
echo "Next steps:"
echo "  1. ./scripts/detect-support-surface.sh \"$PROJECT\""
echo "  2. ./scripts/check-skills.sh \"$OUT/.workspace\""
echo "  3. Run codebase-archaeology + codebase-report on the support paths"
echo "  4. Run voice analysis + POLICY-ELICITATION, then fill 05-policies.md and 08-voice.md"
echo "  5. Replace scripts/list-open.sh with the project-specific open-item pull"
echo "  6. Validate the support map with scripts/validate-support-map.py"
echo "  7. Validate open-item output with scripts/validate-adapter-output.py and run a fire drill"
