#!/usr/bin/env node
// generate-meta.mjs — walk content/ and emit app/_meta.global.tsx
//
// Preserves existing ordering: if an existing _meta.global.tsx is parseable,
// we use its declared order for known keys and append any newly-discovered
// pages at the end of their section.
//
// Usage:
//   generate-meta.mjs [site-dir]
//
// Writes <site-dir>/app/_meta.global.tsx.

import { readdir, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'

const siteDir = process.argv[2] ?? process.cwd()
const contentDir = join(siteDir, 'content')
const metaPath = join(siteDir, 'app', '_meta.global.tsx')

if (!existsSync(contentDir)) {
  console.error(`no content/ dir at ${contentDir}`)
  process.exit(1)
}

async function walk(dir, relativeTo = dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const items = []
  for (const entry of entries) {
    if (entry.name.startsWith('_') || entry.name.startsWith('.')) continue
    const abs = join(dir, entry.name)
    const rel = abs.slice(relativeTo.length + 1)
    if (entry.isDirectory()) {
      items.push({
        kind: 'folder',
        key: entry.name,
        rel,
        items: await walk(abs, relativeTo)
      })
    } else if (entry.isFile() && entry.name.endsWith('.mdx')) {
      const key = entry.name.replace(/\.mdx$/, '')
      if (key === 'index') continue // index is the folder's own page, not a child
      items.push({ kind: 'file', key, rel })
    }
  }
  return items
}

// Parse the existing _meta.global.tsx minimally to extract key order.
async function existingOrder() {
  if (!existsSync(metaPath)) return null
  try {
    const txt = await readFile(metaPath, 'utf8')
    // crude: extract top-level keys in declaration order from the literal object
    const topKeys = []
    const exportMatch = txt.match(/export default\s*\{([\s\S]*)\}\s*satisfies/m)
    if (!exportMatch) return null
    const body = exportMatch[1]
    const re = /^\s*'?([A-Za-z0-9_\-]+)'?\s*:/gm
    let m
    while ((m = re.exec(body)) !== null) topKeys.push(m[1])
    return topKeys
  } catch {
    return null
  }
}

const tree = await walk(contentDir)
const savedOrder = await existingOrder()

// Build top-level meta from content/ root.
const topLevel = {}
for (const item of tree) {
  if (item.kind === 'file') {
    topLevel[item.key] = ''
  } else {
    topLevel[item.key] = { type: 'page', items: flatten(item.items) }
  }
}

// If we have a saved order, reorder known keys to match; then add new ones
// at the end in alphabetical order.
function reorder(record, savedOrder) {
  if (!savedOrder) return record
  const out = {}
  for (const k of savedOrder) if (k in record) out[k] = record[k]
  for (const k of Object.keys(record).sort()) if (!(k in out)) out[k] = record[k]
  return out
}

// Convert our tree into Nextra _meta shape (nested items under folders).
function flatten(items) {
  const out = {}
  for (const item of items) {
    if (item.kind === 'file') {
      out[item.key] = ''
    } else {
      out[item.key] = { items: flatten(item.items) }
    }
  }
  return out
}

const orderedTop = reorder(topLevel, savedOrder)

// Force index to be hidden if present
if (orderedTop.index !== undefined) {
  orderedTop.index = { type: 'page', display: 'hidden' }
}

// Emit TypeScript (JSON-compatible where possible)
function emit(record, indent = 0) {
  const pad = '  '.repeat(indent)
  const inner = Object.entries(record)
    .map(([k, v]) => {
      const key = /^[A-Za-z_][\w]*$/.test(k) ? k : JSON.stringify(k)
      if (v === '' || v === null || v === undefined) return `${pad}  ${key}: ''`
      if (typeof v === 'string') return `${pad}  ${key}: ${JSON.stringify(v)}`
      if (typeof v === 'object') return `${pad}  ${key}: ${emit(v, indent + 1)}`
      return `${pad}  ${key}: ${JSON.stringify(v)}`
    })
    .join(',\n')
  return `{\n${inner}\n${pad}}`
}

const fileContent = `import type { MetaRecord } from 'nextra'

// Auto-generated by scripts/generate-meta.mjs.
// Hand-edits to key order are preserved on re-run.

export default ${emit(orderedTop)} satisfies MetaRecord
`

await writeFile(metaPath, fileContent, 'utf8')
console.log(`wrote ${metaPath}`)
