#!/usr/bin/env bash
# generate-ub-runbook.sh — produce a starter UB_RUNBOOK.md from the workspace
# phase artifacts. Phase 12 invokes this as a scaffold; the orchestrator then
# fills in the project-specific recipes.
#
# Usage: generate-ub-runbook.sh <workspace>
# <workspace> should be <source>/.ub-exorcism/<run-id>/.
set -euo pipefail

case "${1:-}" in
    -h|--help)
        awk 'NR>1 && /^#/{sub(/^# ?/, ""); print; next} NR>1{exit}' "$0"
        exit 0
        ;;
esac

if [[ $# -ne 1 ]]; then
    echo "Usage: generate-ub-runbook.sh <workspace>" >&2
    exit 2
fi

WORKSPACE="$1"

canonicalize_workspace() {
    local workspace_real source_real
    workspace_real="$(realpath -m "$WORKSPACE")"
    case "$workspace_real" in
        */.ub-exorcism/*) ;;
        *)
            echo "Workspace must be inside the audited source repo: <source>/.ub-exorcism/<run-id>" >&2
            echo "Got: $workspace_real" >&2
            exit 64
            ;;
    esac
    source_real="${workspace_real%%/.ub-exorcism/*}"
    source_real="$(realpath -m "$source_real")"
    if [[ ! -f "$source_real/Cargo.toml" ]]; then
        echo "Workspace must be inside a Rust source repo: <source>/.ub-exorcism/<run-id>" >&2
        echo "Expected Cargo.toml at: $source_real/Cargo.toml" >&2
        echo "Got: $workspace_real" >&2
        exit 64
    fi
    case "$workspace_real/" in
        "$source_real"/.ub-exorcism/*) WORKSPACE="$workspace_real" ;;
        *)
            echo "Workspace must be inside the audited source repo: <source>/.ub-exorcism/<run-id>" >&2
            echo "Source: $source_real" >&2
            echo "Got:    $workspace_real" >&2
            exit 64
            ;;
    esac
}

canonicalize_workspace
OUT="$WORKSPACE/UB_RUNBOOK.md"

if [[ -f "$OUT" ]]; then
    echo "$OUT already exists; not overwriting" >&2
    exit 1
fi

# Try to derive project name from phase0_run.json
PROJECT=$(jq -r '.source_path' "$WORKSPACE/phase0_run.json" 2>/dev/null | xargs basename 2>/dev/null || echo "<project>")

cat > "$OUT" <<RUNBOOK
# UB Runbook — Keep $PROJECT UB-Free

Generated by rust-undefined-behavior-exorcist after run $(date -u +%Y-%m-%dT%H:%M:%SZ).

## Minimum Clippy lint group

\`\`\`bash
cargo clippy --all-targets -- \\
  -W clippy::pedantic -W clippy::nursery -W clippy::cargo \\
  -W clippy::undocumented_unsafe_blocks \\
  -W clippy::multiple_unsafe_ops_per_block \\
  -W clippy::cast_ptr_alignment -W clippy::cast_ref_to_mut \\
  -W clippy::invalid_reference_casting \\
  -W clippy::transmute_undefined_repr \\
  -W clippy::uninit_assumed_init \\
  -W clippy::derive_ord_xor_partial_ord \\
  -W clippy::derive_hash_xor_eq \\
  -W clippy::await_holding_lock
\`\`\`

## MIRIFLAGS matrix for CI

\`\`\`yaml
# .github/workflows/ub.yml excerpt
miri-matrix:
  strategy:
    matrix:
      config:
        - { name: default,            flags: "" }
        - { name: tree_borrows,       flags: "-Zmiri-tree-borrows" }
        - { name: strict_provenance,  flags: "-Zmiri-strict-provenance" }
        - { name: symbolic_alignment, flags: "-Zmiri-symbolic-alignment-check" }
  steps:
    - run: MIRIFLAGS="\${{ matrix.config.flags }}" cargo +nightly miri test
\`\`\`

## Sanitizer matrix for CI

\`\`\`yaml
sanitizers:
  strategy:
    matrix:
      sanitizer: [address, thread, leak]
  steps:
    - run: |
        if [[ "\${{ matrix.sanitizer }}" == "thread" ]]; then
          RUSTFLAGS="-Zsanitizer=thread" cargo +nightly test --target x86_64-unknown-linux-gnu -- --test-threads=1
        else
          RUSTFLAGS="-Zsanitizer=\${{ matrix.sanitizer }}" cargo +nightly test --target x86_64-unknown-linux-gnu
        fi
\`\`\`

## Loom models to keep green

(Filled by orchestrator based on phase3_dynamic_findings.md loom rows.)

## Fuzz corpora to preserve

(Filled by orchestrator based on phase3_raw/fuzz_artifacts/.)

## // SAFETY: comment template

\`\`\`rust
// SAFETY:
//   1. <invariant 1; cite where it's enforced>
//   2. <invariant 2>
//   3. <invariant 3 if FFI: alignment, provenance, lifetimes>
unsafe {
    // ... operation that depends on the above invariants ...
}
\`\`\`

## rustc -W flags for project-wide enabling

\`\`\`toml
# In Cargo.toml or .cargo/config.toml
[build]
rustflags = [
    "-W", "unsafe_op_in_unsafe_fn",
    "-W", "unused_unsafe",
    "-W", "invalid_reference_casting",
    "-W", "dangling_pointers_from_temporaries",
    "-W", "unaligned_references",
    "-W", "improper_ctypes",
    "-W", "improper_ctypes_definitions",
]
\`\`\`

## "If you change X, re-run EXP-Y" recipes

(Filled by orchestrator based on phase8_remediation_plan.md cross-references.)
RUNBOOK

chmod 644 "$OUT"
echo "Wrote $OUT"
