#!/usr/bin/env bash
# miri-axis-differ.sh — diff verdicts across the MIRIFLAGS matrix axes.
#
# Reads $WORKSPACE/phase3_raw/miri_{default,tree_borrows,strict_provenance,
# symbolic_alignment}.log (the files emitted by run-miri-matrix.sh)
# and writes $WORKSPACE/phase3_raw/miri_axis_diff.md listing every test whose
# verdict differs across axes.
#
# A divergence is *signal*, not noise: it means one borrow model / provenance
# rule / alignment check accepts a program the other rejects. That's a soundness
# gradient the project owner needs to know about.
#
# Usage: miri-axis-differ.sh <workspace>
#
# Workspace must be inside the audited source: <source>/.ub-exorcism/<run-id>/
# Exit codes:
#   0 — no divergences found; the matrix is uniform
#   1 — divergences found; see the diff report
#   2 — fatal (missing input logs, invalid workspace, etc.)
set -euo pipefail

case "${1:-}" in
    -h|--help)
        awk 'NR>1 && /^#/{sub(/^# ?/, ""); print; next} NR>1{exit}' "$0"
        exit 0
        ;;
esac

if [[ $# -ne 1 ]]; then
    echo "Usage: miri-axis-differ.sh <workspace>" >&2
    exit 2
fi

WORKSPACE="$1"

# Canonicalize + validate the workspace path (same pattern as run-miri-matrix.sh)
WORKSPACE_REAL="$(realpath -m "$WORKSPACE")"
case "$WORKSPACE_REAL" in
    */.ub-exorcism/*) ;;
    *)
        echo "Workspace must be inside <source>/.ub-exorcism/<run-id>" >&2
        echo "Got: $WORKSPACE_REAL" >&2
        exit 2
        ;;
esac
WORKSPACE="$WORKSPACE_REAL"

RAW="$WORKSPACE/phase3_raw"
if [[ ! -d "$RAW" ]]; then
    echo "phase3_raw/ not found under $WORKSPACE — run scripts/run-miri-matrix.sh first" >&2
    exit 2
fi

AXES=( default tree_borrows strict_provenance symbolic_alignment )
MISSING=()
for axis in "${AXES[@]}"; do
    if [[ ! -f "$RAW/miri_${axis}.log" ]]; then
        MISSING+=("$axis")
    fi
done
if [[ "${#MISSING[@]}" -gt 0 ]]; then
    echo "Missing axis logs: ${MISSING[*]}" >&2
    echo "Run scripts/run-miri-matrix.sh to populate them." >&2
    exit 2
fi

# Extract per-test verdicts. Cargo+Miri output looks like:
#   test foo::bar ... ok
#   test foo::baz ... FAILED
# Some runs prefix with "test [tokio::test]" — handle both. We don't try to
# parse mid-test panic traces; the simple "ok"/"FAILED" tail is the verdict
# the Rust test harness emits per test.
extract_verdicts() {
    local logfile="$1"
    # Capture lines of the form "test NAME ... VERDICT"; tolerate leading
    # whitespace and the optional "test" prefix in nested-harness output.
    awk '
        /^test [^ ]+ \.\.\. (ok|FAILED|ignored)$/ {
            name=$2; verdict=$NF;
            print name "\t" verdict;
        }
    ' "$logfile" | sort -u
}

TMPDIR_HERE="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_HERE"' EXIT

for axis in "${AXES[@]}"; do
    extract_verdicts "$RAW/miri_${axis}.log" > "$TMPDIR_HERE/${axis}.tsv"
done

AXES_WITHOUT_CONCRETE=()
for axis in "${AXES[@]}"; do
    concrete_on_axis="$(awk -F'\t' '$2 == "ok" || $2 == "FAILED" { n++ } END { print n+0 }' "$TMPDIR_HERE/${axis}.tsv")"
    if [[ "$concrete_on_axis" -eq 0 ]]; then
        AXES_WITHOUT_CONCRETE+=("$axis")
    fi
done

# Build a join: union of test names across axes, columns = verdict per axis
# (or "—" if the test didn't run / wasn't observed on that axis).
ALL_NAMES="$TMPDIR_HERE/all_names.txt"
cut -f1 "$TMPDIR_HERE"/*.tsv | sort -u > "$ALL_NAMES"

# Build a per-test row and check for divergence
OUT="$RAW/miri_axis_diff.md"
{
    printf '# Miri axis verdict diff\n\n'
    printf 'Generated by `scripts/miri-axis-differ.sh` from `phase3_raw/miri_*.log`.\n\n'
    printf '| Test | default | tree_borrows | strict_provenance | symbolic_alignment | Divergent? |\n'
    printf '|------|---------|--------------|-------------------|--------------------|------------|\n'
} > "$OUT"

DIVERGENT_COUNT=0
TOTAL_COUNT=0
CONCRETE_VERDICT_COUNT=0
INCOMPLETE_COVERAGE_COUNT=0
while read -r name; do
    [[ -z "$name" ]] && continue
    TOTAL_COUNT=$((TOTAL_COUNT + 1))
    row_cells=()
    verdicts_seen=()
    for axis in "${AXES[@]}"; do
        # Find the verdict line for $name in $axis.tsv; default to "—"
        v="$(awk -F'\t' -v n="$name" '$1==n { print $2; exit }' "$TMPDIR_HERE/${axis}.tsv")"
        v="${v:-—}"
        row_cells+=("$v")
        # Only count concrete verdicts (skip "—" and "ignored") when judging divergence
        case "$v" in
            ok|FAILED)
                verdicts_seen+=("$v")
                CONCRETE_VERDICT_COUNT=$((CONCRETE_VERDICT_COUNT + 1))
                ;;
        esac
    done

    # Divergent iff more than one distinct concrete verdict
    distinct=0
    if [[ "${#verdicts_seen[@]}" -gt 0 ]]; then
        distinct="$(printf '%s\n' "${verdicts_seen[@]}" | sort -u | wc -l | tr -d ' ')"
    fi
    concrete_for_test="${#verdicts_seen[@]}"
    incomplete_for_test="no"
    if [[ "$concrete_for_test" -gt 0 && "$concrete_for_test" -lt "${#AXES[@]}" ]]; then
        incomplete_for_test="yes"
        INCOMPLETE_COVERAGE_COUNT=$((INCOMPLETE_COVERAGE_COUNT + 1))
    fi
    if [[ "$distinct" -gt 1 ]]; then
        marker="**YES**"
        DIVERGENT_COUNT=$((DIVERGENT_COUNT + 1))
    elif [[ "$incomplete_for_test" == "yes" ]]; then
        marker="incomplete"
    else
        marker="no"
    fi

    printf '| `%s` | %s | %s | %s | %s | %s |\n' \
        "$name" "${row_cells[0]}" "${row_cells[1]}" "${row_cells[2]}" "${row_cells[3]}" \
        "$marker" >> "$OUT"
done < "$ALL_NAMES"

# Summary footer. Use `printf --` to terminate option processing because the
# bullet lines start with `-`, which printf would otherwise try to consume.
{
    printf '\n## Summary\n\n'
    printf -- '- Tests observed across all axes: %d\n' "$TOTAL_COUNT"
    printf -- '- Concrete ok/FAILED verdicts observed: %d\n' "$CONCRETE_VERDICT_COUNT"
    printf -- '- Tests with incomplete concrete coverage: %d\n' "$INCOMPLETE_COVERAGE_COUNT"
    if [[ "${#AXES_WITHOUT_CONCRETE[@]}" -gt 0 ]]; then
        printf -- '- Axes with zero concrete verdicts: %s\n' "${AXES_WITHOUT_CONCRETE[*]}"
    fi
    printf -- '- Tests with divergent verdicts: **%d**\n' "$DIVERGENT_COUNT"
    if [[ "$CONCRETE_VERDICT_COUNT" -eq 0 ]]; then
        printf '\nNo concrete Rust test-harness ok/FAILED verdicts were found in the Miri logs. This usually means the logs are empty, compilation failed before tests ran, every observed test was ignored, or the output format changed. Inspect `phase3_raw/miri_*.log` before treating the matrix as clean.\n'
    elif [[ "$DIVERGENT_COUNT" -gt 0 ]]; then
        printf '\nEach divergent test is a candidate Phase 5 experiment: one axis accepts a program the other rejects. That asymmetry is a soundness gradient, not noise. Open a Phase 5 entry in `UNDEFINED_BEHAVIOR_EXPERIMENT_DESIGNS.md` for each, citing the divergent axes.\n'
    elif [[ "$INCOMPLETE_COVERAGE_COUNT" -gt 0 || "${#AXES_WITHOUT_CONCRETE[@]}" -gt 0 ]]; then
        printf '\nThe Miri matrix has incomplete concrete verdict coverage. Inspect the axes/tests marked `incomplete` before treating the matrix as clean; a missing verdict often means an axis failed before the Rust test harness emitted per-test results.\n'
    else
        printf '\nThe Miri matrix is verdict-uniform. No further investigation needed from this detector.\n'
    fi
} >> "$OUT"

echo "Wrote $OUT"
echo "  Tests observed: $TOTAL_COUNT"
echo "  Concrete ok/FAILED verdicts: $CONCRETE_VERDICT_COUNT"
echo "  Tests with incomplete concrete coverage: $INCOMPLETE_COVERAGE_COUNT"
if [[ "${#AXES_WITHOUT_CONCRETE[@]}" -gt 0 ]]; then
    echo "  Axes with zero concrete verdicts: ${AXES_WITHOUT_CONCRETE[*]}"
fi
echo "  Divergent verdicts: $DIVERGENT_COUNT"

if [[ "$CONCRETE_VERDICT_COUNT" -eq 0 ]]; then
    echo "No concrete Miri test verdicts found; axis diff is inconclusive." >&2
    exit 2
fi
if [[ "$DIVERGENT_COUNT" -gt 0 ]]; then
    exit 1
fi
if [[ "$INCOMPLETE_COVERAGE_COUNT" -gt 0 || "${#AXES_WITHOUT_CONCRETE[@]}" -gt 0 ]]; then
    echo "Miri axis verdict coverage is incomplete; axis diff is inconclusive." >&2
    exit 2
fi
exit 0
