#!/usr/bin/env bash
# regenerate-fixture.sh — Re-create one fixture's expected-output file by
# running the audit fresh against the fixture and capturing the result.
#
# Usage:
#   regenerate-fixture.sh <fixture-name> [--threshold 700]
#
# When you change the rubric or theater patterns and the audit's output
# *legitimately* shifts, you regenerate fixtures whose EXPECTED.md should
# now reflect the new behavior. CAUTION: this overwrites EXPECTED.md, so
# the new file becomes the new ground truth — review the diff before
# committing.
#
# Workflow:
#   1. Stash the current EXPECTED.md (so you can diff afterward).
#   2. Run the fixture's seed.sh in a tmp dir.
#   3. Audit it.
#   4. Extract assertions from the resulting REPORT.md and write a fresh
#      EXPECTED.md (with `## Assertions` formatted for compare-to-expected).
#   5. Print the diff vs the stashed EXPECTED.md so you can review.
#
# Exit codes:
#   0  fixture regenerated; review the diff
#   2  invalid arguments / fixture not found
case "${1:-}" in --help|-h) awk '/^[^#]/&&NR>1{exit} NR>1{sub(/^# ?/,"");print}' "$0"; exit 0 ;; esac
set -uo pipefail

FIXTURE_NAME="${1:?fixture name required (e.g. known-good)}"
shift || true

THRESHOLD=700
require_value() { if [ "$2" -lt 2 ]; then echo "ERROR: $1 requires a value" >&2; exit 2; fi; }
while [ $# -gt 0 ]; do
  case "$1" in
    --threshold) require_value "$1" "$#"; THRESHOLD="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPTS="$SKILL_DIR/scripts"
FIXTURE_DIR="$SKILL_DIR/assets/fixtures/$FIXTURE_NAME"
[ -d "$FIXTURE_DIR" ] || { echo "ERROR: fixture not found: $FIXTURE_DIR" >&2; exit 2; }
[ -f "$FIXTURE_DIR/seed.sh" ] || { echo "ERROR: $FIXTURE_DIR/seed.sh missing" >&2; exit 2; }

echo "── regenerating: $FIXTURE_NAME ──"

# 1. Stash current EXPECTED.md.
EXPECTED="$FIXTURE_DIR/EXPECTED.md"
PRIOR=""
if [ -f "$EXPECTED" ]; then
  PRIOR="$(mktemp)"
  # Retain the prior snapshot for diagnosis if regeneration fails or produces a
  # disputed diff. This repo forbids agents from deleting files.
  cp "$EXPECTED" "$PRIOR"
  echo "  stashed prior EXPECTED.md → $PRIOR"
fi

# 2. Seed in tmp.
TMP="/tmp/regen-fixture-${FIXTURE_NAME}-$(date -u +%s)"
mkdir -p "$TMP"
( cd "$TMP" && bash "$FIXTURE_DIR/seed.sh" >/dev/null 2>&1 ) || {
  echo "ERROR: seed.sh failed for $FIXTURE_NAME" >&2; exit 2;
}

# 3. Audit.
"$SCRIPTS/run-pass.sh" "$TMP" --threshold "$THRESHOLD" --policy report-only \
  >"$TMP/_audit.stdout" 2>"$TMP/_audit.stderr" || true
AUDIT="${TMP}/beads_compliance_audit"
[ -f "$AUDIT/REPORT.md" ] || { echo "ERROR: audit produced no REPORT.md" >&2; exit 2; }

# 4. Derive assertions from REPORT.md. We use python to extract structured
#    facts so the formatting is consistent with what compare-to-expected
#    expects.
python3 - "$AUDIT/REPORT.md" "$THRESHOLD" "$FIXTURE_NAME" > "$EXPECTED" <<'PY'
import re, sys
from pathlib import Path
report_path, threshold, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
txt = Path(report_path).read_text()

def find(pat, default=None):
    m = re.search(pat, txt, re.I)
    return int(m.group(1)) if m else default

# Match the `master-report.py` exec-summary line:
#   "**N** total beads audited; **M** false-closed (...) — **P%** of all
#    closed beads (of K total closed)."
# Plus the header line: "Beads audited: N  |  Threshold: 700"
total = find(r"\*\*(\d+)\*\*\s+total beads audited") or find(r"Beads audited:\s*(\d+)") or 0
closed = find(r"of\s+(\d+)\s+total closed") or 0
fc = find(r"\*\*(\d+)\*\*\s+false[- ]closed") or 0

# False-closed bead ids
fc_ids: list[str] = []
in_fc = False
for line in txt.splitlines():
    if line.startswith("## False-closed list"):
        in_fc = True; continue
    if in_fc and line.startswith("## "): in_fc = False
    if in_fc:
        m = re.match(r"^\|\s*`([a-z][a-z0-9_.-]*)`", line)
        if m: fc_ids.append(m.group(1))

print(f"# EXPECTED — fixture `{name}`")
print()
print(f"_Regenerated by `scripts/regenerate-fixture.sh` against threshold={threshold}._")
print()
print("## Assertions")
print()
print(f"- total_beads: {total}")
print(f"- closed_count: {closed}")
print(f"- false_closed_count: {fc}")
for bid in sorted(fc_ids):
    print(f"- false_closed_includes: {bid}")
PY

# 5. Diff.
if [ -n "$PRIOR" ]; then
  echo
  echo "── diff vs prior EXPECTED.md ──"
  diff -u "$PRIOR" "$EXPECTED" || true
  echo "  retained prior EXPECTED.md snapshot at $PRIOR"
fi

echo
echo "✓ regenerated: $EXPECTED"
echo "  Review the diff. If correct, commit. If not, fix the rubric/scorer/seed.sh."
